;;; entropy-global-read-only-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-global-read-only-mode.el

(autoload 'entropy/grom-read-only-buffer "entropy-global-read-only-mode" nil t)
(autoload 'entropy/grom-toggle-read-only "entropy-global-read-only-mode" "\
Toggle readonly-or-not for all buffers except for the
buffer-name witin the full buffer name regexp matching by
`entropy/grom-buffer-special-p'.

There's four optional argument for this function:

- *readonly and editted:* If set one of them to 't' then means
  'toggle read only' or 'toggle editted' independently

- *current-buffer-ndwp:* This set for prompting whether do the
  main specific function in current buffer when it set to nil . It
  means that not do with current buffer and be with prompt. This
  set will cover cury setting when it's be nil.

- *cury:* Do with current buffer without prompt if set it and
  =current-buffer-ndwp= to t,
  opposite means that not do current buffer.

(fn &optional READONLY EDITTED CURRENT-BUFFER-NDWP CURY)" t)
(autoload 'entropy/grom-quick-readonly-global "entropy-global-read-only-mode" "\
Do readonly for all buffers include current-buffer.

This function are basically rely on `entropy/grom-toggle-read-only'." t)
(defvar entropy-grom-mode nil "\
Non-nil if Entropy-GROM mode is enabled.
See the `entropy-grom-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `entropy-grom-mode'.")
(custom-autoload 'entropy-grom-mode "entropy-global-read-only-mode" nil)
(autoload 'entropy-grom-mode "entropy-global-read-only-mode" "\
Global minor mode for buffer-readonly for all.

This is a global minor mode.  If called interactively, toggle the
`Entropy-GROM mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='entropy-grom-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "entropy-global-read-only-mode" '("entropy/grom-"))

;;; End of scraped data

(provide 'entropy-global-read-only-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-global-read-only-mode-autoloads.el ends here
