;;; entropy-portableapps-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-portableapps.el

(autoload 'entropy/poapps-query-open "entropy-portableapps" "\
Query and open portableapps." t)
(register-definition-prefixes "entropy-portableapps" '("entropy/poapps-"))

;;; End of scraped data

(provide 'entropy-portableapps-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-portableapps-autoloads.el ends here
