;;; wudao-query-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))


;;;### (autoloads nil "wudao-query" "wudao-query.el" (26829 11924
;;;;;;  859677 615000))
;;; Generated autoloads from wudao-query.el

(autoload 'wudao/query-word-by-hash "wudao-query" "\


\(fn QUERY &optional FULL)")

(autoload 'wudao/query-word-by-hash/use-json-parse "wudao-query" "\


\(fn QUERY &optional FULL)")

(register-definition-prefixes "wudao-query" '("wudao/query-"))

;;;***

;;; End of scraped data

(provide 'wudao-query-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wudao-query-autoloads.el ends here
