;; -*- lexical-binding: t; -*-
;; * common lib
(defun wudao/lib-message (message &rest args)
  (if (fboundp 'entropy/emacs-message-do-message)
      (entropy/emacs-message-do-message
       message args)
    (apply 'message message args)))

(defmacro wudao/lib-with-temp-buffer (&rest body)
  "Like `with-temp-buffer' but press all hook related
`kill-buffer' after body done so that we can say it real
temporally do and have better performance than origin."
  (declare (indent 0) (debug t))
  (let ((temp-buffer (make-symbol "temp-buffer")))
    `(let ((kill-buffer-hook nil)
           (kill-buffer-query-functions nil)
           (,temp-buffer (generate-new-buffer " *temp*")))
       ;; `kill-buffer' can change current-buffer in some odd cases.
       (with-current-buffer ,temp-buffer
         (unwind-protect
             (progn ,@body)
           (and (buffer-name ,temp-buffer)
                (kill-buffer ,temp-buffer)))))))


;; * Compress or decompress file

(defvar wudao/lib--archive-dowith-alist
  '((tar
     :compress "tar -cf %o %i"
     :extract  "tar -xf %i -C %o")
    (tgz
     :compress "tar -zcf %o %i"
     :extract  "tar -zxf %i -C %o")
    (txz
     :compress "tar -Jcf %o %i"
     :extract  "tar -Jxf %i -C %o")
    (t7z
     :compress "tar -cf - %i | 7z a -si %o"
     :extract  "7z x -so %i | tar -xf - -C %o")
    (zip
     :compress "zip %o -r --filesync %i"
     :extract  "unzip -o %i -d %o")))

;; FIXME: the replace may cover the filename which include the pseudo
;; substitution
(defun wudao/lib--gen-archive-dowith-shell-command
    (archive-type input output dowith)
  "Generate a shell command to do with an archive dealing
procedure type DOWITH for archive type ARCHIVE-TYPE of the input
file name INPUT. The shell command also want a output file name
OUTPUT.

The ARCHVE-TYPE can be one of internal support archive type that:
1) 'tar' type: in which case, INPUT was a tar file commonly named
   with \".tar\" as its suffix name.

2) 'tgz' type: in which case, INPUT was a tar file compressed with
   \"gzip\" method and commonly named with \".tgz\" or \".tar.gz\"
   as its suffix name.

3) 'txz' type: in which case, INPUT was a tar file compressed with
   \"xz\" method and commonly named with \".txz\" or \".tar.xz\"
   as its suffix name.

4) 't7z' type: in which case, INPUT was a tar file compressed with
   \"7z\" method and commonly named with \".t7z\" or \".tar.7z\"
   as its suffix name.

5) 'zip' type: in which case, INPUT was a zipper compressed file
   commonly named with \".zip\" as its suffix name.
"
  (let* ((archive-dowith-plist
          (alist-get archive-type
                     wudao/lib--archive-dowith-alist))
         (command-fmstr
          (plist-get archive-dowith-plist dowith)))
    (replace-regexp-in-string
     "%o" (shell-quote-argument output)
     (replace-regexp-in-string
      "%i" (shell-quote-argument input)
      command-fmstr nil t)
     nil t)))

(defun wudao/lib-archive-dowith
    (archive-type input output dowith)
  "Process a file archive procedure using the shell command
generated by `wudao/lib--gen-archive-dowith-shell-command'
with a success message prompt (i.e. commonly non-nil return) when
command executed successfully or throw out an `user-error'
otherwise.

The arguments list is the same as thus of
`wudao/lib--gen-archive-dowith-shell-command', see it for
their usage."
  (if (= 0 (call-process-shell-command
            (wudao/lib--gen-archive-dowith-shell-command
             archive-type input output dowith)))
      (message "%s file %s to %s successfully"
               (if (eq dowith :compress)
                   "Compress"
                 "Uncompress")
               input output)
    (user-error "%s file %s to %s with fatal ⚠"
                (if (eq dowith :compress)
                    "Compress"
                  "Uncompress")
                input output)))

;; * provide
(provide 'wudao-lib)
