;;; wudao-query-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:
(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))


;;; Generated autoloads from wudao-json-cache.el

(register-definition-prefixes "wudao-json-cache" '("wudao/json-cache-"))


;;; Generated autoloads from wudao-lib.el

(register-definition-prefixes "wudao-lib" '("wudao/lib-"))


;;; Generated autoloads from wudao-query.el

(autoload 'wudao/query-word-by-hash/use-json-parse "wudao-query"
"

(fn QUERY &optional FULL)")
(autoload 'wudao/query-word-by-command/use-json-parse "wudao-query"
"

(fn QUERY &optional FULL)")

;;; End of scraped data

(provide 'wudao-query-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; wudao-query-autoloads.el ends here
