# Created 2019-09-06 Fri 19:57
#+TITLE: Url proxy for emacs eww and w3m
#+AUTHOR: entropy

* Copyright (C) 20190906  Entropy
#+BEGIN_EXAMPLE
Author:        Entropy <bmsac0001@gmail.com>
Maintainer:    Entropy <bmsac001@gmail.com>
URL:           https://github.com/c0001/entropy-proxy-url/
Package-Version: v0.1.0
Created:       2018
Keywords:      proxy
Compatibility: GNU Emacs emacs-version;
Package-Requires: ((emacs "26") (cl-lib "0.5"))

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
#+END_EXAMPLE

* Commentary:

An emacs extension trafficking url matching by proxy regxp rule-set or
pull down them into whole proxy tunnel.

This package perform as the library role for the functional provision.

** Eww and emacs-w3m proxy stuff

Emacs has the ability to retrieving network data steps with internal
func ~url-retrieve~ and it's refer url library as. Eww using it as the
communication backend.

Although, there's another way for emacs to get network data througha
the way of using external shell application which obtains its
responsing as the render part. One as be in this case was the famous
cli plain text browser [[http://w3m.sourceforge.net/][w3m]].

The proxy way for the internal data retrieve was based on emacs
internal proxy mechanism, and the other one was based on the refer
response creator's self mechanism.

** How this package working as?

This package taking off the proxy way through two ways for as:

1. Regexp matching of current url retrieving.
2. Full proxy tunnel whichever current transfer url is.

As seen as which are easy to understanding of the full proxy
type,here's the description for 'regexp' way:

Each network transfer request will come with one url string as the
requesting wrapper header. URL string has it's feature stored in it's
domain part, the domain part can be matched by categorizing using
regexp method, thus each network requesting can be filter by sets of
regexp rule-set for determining whether go into the proxy tunnerl.

The regexp filter can be generized of more functional part, by
matching whatever you want. The rule-set internal customized variable
=entropy/proxy-url-gfw-regexp-alist= as is.

This package use the [[https://github.com/gfwlist/gfwlist][gfwlist]] as the default ruleset, for the original
prototype for it was the simple variant of [[https://en.wikipedia.org/wiki/Proxy_auto-config][PAC]](proxy auto
configuration), whose syntax abided by [[https://adblockplus.org/][adblock-plus]] web extensions,
for that reason to use this was that gfwlist was originally used for
the webbrowser extensions for doing thus as what you have known for
the internet charging among on CHINA. Thus for that, this package
requires one =PAC= analyzer as now I use the another [[https://github.com/c0001/entropy-emacs][entropy-emacs]]
specific package [[https://github.com/c0001/entropy-adblockP-rule-analysis][entropy-adblock+-rule-analysis]] to role as the gfwlist
anaylizer, it will auto fetch the latest version gfwlist if possible
when you current internet environment allow the connecting for that,
or using the package built-in one which was the pre-fetched one, so it
will not be the latest version.

** Methods given

We using property list as a =PROXY-RECIPE= to given the customized
way for specify the proxy subroutine.

As the focurs on, the =PROXY-RECIPE= mainly use ~advice-add~ to
around wrappering the target underline functional commands, like
~w3m-goto-url~ , ~url-retrieve~ etc.

The =PROXY-RECIPE= slots valid for those listed below:

- =:group-name= : a symbol to indicate the recipe name
  identification

- =:advice-fors= : list of functions for be wrappered with
  `entropy/proxy-url` specification

- =:type-source= : a symbol restored the proxy type (i.e. which
  described in `entropy/proxy-url-initial-typesource')

- =:PROXY-MECHANISM= : a symbol indicate the proxy mechanism
  (i.e. describe for `entropy/proxy-url-default-proxy-server-obj')

- =:server-host-alist= : a symbol indicate the proxy server host
  alist which using the same struct with
  `entropy/proxy-url-default-proxy-server-obj'"

- =:bind= : a alist which the each car of the element was the
  key-map and the cdr was the keybinding specific valid as the
  form for =kbd= function.

** Proxy reset

For those cases that you want to quickly reset the proxy server,
just reset your recipes =:server-host-alist= slot's symbol value,
all functional form will obtain the new proxy-host value at next
time for proxy-connection doing.

* Configuration:

Just require it, and building =PROXY-RECIPE= you specified.

** Target operation advice

There're two built-in =proxy-recipe= i.e. the
~entropy/proxy-url--eww-recipe~ and
~entropy/proxy-url--w3m-recipe~, you can call function
~entropy/proxy-url-make-builtin-recipes~ to buiding
them. Futhermore you can specify your own recipe follow what
mentioned above, and use function ~entropy/proxy-url-make-recipes~
to buiding it(see its doc-string for more details).

** customized varaibles

See customized-variable-group ~entropy/proxy-url-group~ for them.

** The regexp rule-set list data

Internally, =entropy-proxy-url= has given the sets of regexp rule set
tracking by [[https://github.com/gfwlist/gfwlist][github gfw list]] project which maintained the common
sensible blocked web domain list directed against to China GFW network
ecosystem, however I thought as be compatible for some web transfer
chargin area too of that China as the biggest aspect doing for thus.
The gfw-rule analyzing provided by [[https://github.com/c0001/entropy-adblockP-rule-analysis][entropy-adbp+-rule-analysis]] package
(Add it to ~load-path~ was requested also).

