((:subtree "elements/site-lisp/entropy-adblockP-rule-analysis"
           :upstream "https://github.com/c0001/entropy-adblockP-rule-analysis.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-project-manager"
           :upstream "https://github.com/c0001/entropy-project-manager.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-unfill"
           :upstream "https://github.com/c0001/entropy-unfill.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-sdcv"
           :upstream "https://github.com/c0001/entropy-sdcv.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-s2t"
           :upstream "https://github.com/c0001/entropy-s2t.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-proxy-url"
           :upstream "https://github.com/c0001/entropy-proxy-url.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-portableapps"
           :upstream "https://github.com/c0001/entropy-portableapps.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-org-widget"
           :upstream "https://github.com/c0001/entropy-org-widget.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-org-export-theme-toggle"
           :upstream "https://github.com/c0001/entropy-org-export-theme-toggle.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-org-batch-refile"
           :upstream "https://github.com/c0001/entropy-org-batch-refile.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-open-with"
           :upstream "https://github.com/c0001/entropy-open-with.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-global-read-only-mode"
           :upstream "https://github.com/c0001/entropy-global-read-only-mode.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-font-lock-plus"
           :upstream "https://github.com/c0001/entropy-font-lock-plus.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-epub2org"
           :upstream "https://github.com/c0001/entropy-epub2org.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-en-words"
           :upstream "https://github.com/c0001/entropy-en-words.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-emacs-doc"
           :upstream "https://github.com/c0001/entropy-emacs-doc.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-dired-cp-or-mv"
           :upstream "https://github.com/c0001/entropy-dired-cp-or-mv.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-counsel-stuffs"
           :upstream "https://github.com/c0001/entropy-counsel-stuffs.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-common-library"
           :upstream "https://github.com/c0001/entropy-common-library.git"
           :ref "master")
 (:subtree "elements/site-lisp/entropy-cn-dict"
           :upstream "https://github.com/c0001/entropy-cn-dict.git"
           :ref "master")
 (:subtree "elements/site-lisp/liberime"
           :upstream "https://gitlab.com/liberime/liberime.git"
           :ref "master")
 (:subtree "elements/site-lisp/fakecygpty"
           :upstream "https://github.com/d5884/fakecygpty.git"
           :ref "master"))
