;;; entropy-dired-cp-or-mv-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-dired-cp-or-mv.el

(autoload 'entropy/cpmv-dired-get-files-list "entropy-dired-cp-or-mv" "\
Get files list for cp or mv for `entropy/cpmv-to-current' with
checked buffer showing" t)
(autoload 'entropy/cpmv-to-current "entropy-dired-cp-or-mv" "\
Cp or Mv fils or directory of file-list created by
`entropy/cpmv-dired-get-files-list' with checked buffer showing" t)
(register-definition-prefixes "entropy-dired-cp-or-mv" '("entropy/cpmv--"))

;;; End of scraped data

(provide 'entropy-dired-cp-or-mv-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-dired-cp-or-mv-autoloads.el ends here
