;;; entropy-proxy-url-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-proxy-url.el

(autoload 'entropy/proxy-url-make-recipes "entropy-proxy-url" "\
Expand proxy-sepcification to its defination, grouped as RECIPE.

The recipe was one plist.

Recipe slots:

- `:group-name' : a symbol to indicate the recipe name identification

- `:advice-fors' : list of functions for be `adviced-add' with
  `entropy-proxy-url' specification.

- `:type-source' : a symbol restored the proxy type (i.e. which
  described in `entropy/proxy-url-initial-typesource')

- `:proxy-mechanism' : a symbol indicate the proxy mechanism
  (i.e. describe for `entropy/proxy-url-default-proxy-server-alist')

- `:server-host-alist' : a alist described for supported proxy types
  which using the same structure as
  `entropy/proxy-url-default-proxy-server-alist' but just matched only
  for curent `:proxy-mechanism'

- `:bind' : a cons for the car of a list of feature to lazy load and
  the cdr of a alist for keymap and keybind stroke specification,
  keybind-key form as function `kbd' does.

(fn PROXY-RECIPES &optional UNMAKE)")
(autoload 'entropy/proxy-url-make-builtin-recipes "entropy-proxy-url" "\


(fn &optional UNMAKE)")
(autoload 'entropy/proxy-url-update-proxy-port "entropy-proxy-url" "\
Quickly toggle proxy host port via each element of
`entropy/proxy-url-default-proxy-server-alist'." t)
(defalias 'entropy/proxy-url-with-url-proxy 'entropy/proxy-url--with-url-proxy)
(register-definition-prefixes "entropy-proxy-url" '("entropy/proxy-url-"))

;;; End of scraped data

(provide 'entropy-proxy-url-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-proxy-url-autoloads.el ends here
