;;; company-en-words-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-en-words.el

(register-definition-prefixes "company-en-words" '("company-en-words"))


;;; Generated autoloads from company-en-words-data.el

(register-definition-prefixes "company-en-words-data" '("company-en-words-data/en-words-simple-list"))

;;; End of scraped data

(provide 'company-en-words-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-en-words-autoloads.el ends here
