;;; fakecygpty-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from fakecygpty.el

(autoload 'fakecygpty-activate "fakecygpty" "\
Activate fakecygpty features." t)
(autoload 'fakecygpty-deactivate "fakecygpty" "\
Deactivate fakecygpty features." t)
(register-definition-prefixes "fakecygpty" '("fakecygpty-"))

;;; End of scraped data

(provide 'fakecygpty-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; fakecygpty-autoloads.el ends here
