;;; entropy-open-with-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-open-with.el

(autoload 'entropy/open-with-interactively "entropy-open-with" "\
Interactively calling `entropy/open-with-port'" t)
(autoload 'entropy/open-with-dired-open "entropy-open-with" "\
Dired open with portable apps.

It's core function is `entropy/open-with-match-open', see it for
details.

Optional argument PREFIX if doubled i.e. eq '(16):

- we use `dired-get-marked-files' to matched files and batch open
  them, otherwise we just open the file at current line e.g. get
  the filename by `dired-get-filename'.

(fn &optional PREFIX)" t)
(autoload 'entropy/open-with-buffer "entropy-open-with" "\
Buffer of `current-buffer' open with portable apps.

It's core function is `entropy/open-with-match-open', see it for
details." t)
(register-definition-prefixes "entropy-open-with" '("__entropy/open-with-microsoft-windows-wsl2-env-p" "entropy/open"))

;;; End of scraped data

(provide 'entropy-open-with-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-open-with-autoloads.el ends here
