;;; entropy-org-export-theme-toggle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-org-export-theme-toggle.el

(autoload 'entropy/org-exptth-set-head "entropy-org-export-theme-toggle" "\
Setting `org-html-head' with themes specified by
`entropy-org-export-theme-toggle.el'." t)
(register-definition-prefixes "entropy-org-export-theme-toggle" '("entropy/org-exptt"))

;;; End of scraped data

(provide 'entropy-org-export-theme-toggle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-org-export-theme-toggle-autoloads.el ends here
