;;; liberime-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from liberime.el

(autoload 'liberime-open-user-data-dir "liberime" "\
Open user data dir with external app." t)
(autoload 'liberime-open-shared-data-dir "liberime" "\
Open shared data dir with external app." t)
(autoload 'liberime-open-package-directory "liberime" "\
Open liberime library directory with external app." t)
(autoload 'liberime-open-package-readme "liberime" "\
Open liberime library README.org." t)
(autoload 'liberime-build "liberime" "\
Build liberime-core module." t)
(autoload 'liberime-load "liberime" "\
Load liberime-core module." t)
(autoload 'liberime-deploy "liberime" "\
Deploy liberime to affect config file change." t)
(autoload 'liberime-set-page-size "liberime" "\
Set rime page-size to PAGE-SIZE or by default 10.
you also need to call `liberime-deploy' to make it take affect
you only need to do this once.

(fn PAGE-SIZE)" t)
(autoload 'liberime-select-schema-interactive "liberime" "\
Select a rime schema interactive." t)
(autoload 'liberime-sync "liberime" "\
Sync rime user data.
User should specify sync_dir in installation.yaml file of
`liberime-user-data-dir' directory." t)
(register-definition-prefixes "liberime" '("liberime-"))


;;; Generated autoloads from liberime-test.el

(register-definition-prefixes "liberime-test" '("measure-time"))

;;; End of scraped data

(provide 'liberime-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; liberime-autoloads.el ends here
