;;; entropy-code2org-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-code2org.el

(autoload 'entropy/code2org-convert-current-buffer "entropy-code2org" "\
Convert current buffer into org-mode context and focus on the
transferred buffer." t)
(register-definition-prefixes "entropy-code2org" '("entropy/code2org-"))

;;; End of scraped data

(provide 'entropy-code2org-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-code2org-autoloads.el ends here
