# Created 2019-09-11 Wed 06:36
#+TITLE: Common library for entropy-emacs elisp programming
#+AUTHOR: entropy

* Copyright (C) 20190911  Entropy
#+BEGIN_EXAMPLE
Author:           Entropy <bmsac0001@gmail.com>
Maintainer:       Entropy <bmsac001@gmail.com>
URL:              https://github.com/c0001/entropy-common-library
Package-Version:  0.1.3
Created:          2018-10-08
Package-Requires: ((emacs "25") (dash "2.16.0") (ivy "0.12.0"))

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
#+END_EXAMPLE

* Commentary:

Common elisp library for [[https://github.com/c0001/entropy-emacs][entropy-emacs]].

This package also was the basic dependency for all 'entropy-' ethnic
emacs extension, used for dealing with sets of basic emacs internal
basic func's improvement or the public functional extra specified as.

These specified funcs group seperated as groups of:
- elisp data refer
- file and dir refer
- window and buffer refer
- ivy completion framwork extension
- mischellaneous

** Requirements

- dash (melpa install)
- cl(emacs built-in with already)
- ivy (melpa install)

There's just these three library required for compiling with, simplify
and easy to use.

* Configuration

Just requiring with, do not using lazy laoding of it because of that
all the funcs defined in this package are not defined with =autoload=
macro denoted.



* Change log:
- [2019-11-12]

  *version 0.1.3 release*

  Add new plist manipulate api `entropy/cl-plist-get-rest'.

- [2019-11-11]

  *version 0.1.2 release*

  1. Optimize `entropy/cl-truncate-string-with-length' to use
     emacs-builtin `fill-paragraph' function.

  2. Remove `entropy/cl-truncate-single-line-string-with-length'.

- [2019-11-11]

  *Version 0.1.1 release*

  This is the typo fixed emergency release.

- [2018-10-08]

  *Versions 0.1.0 release*

  First release out.
