;;; entropy-sdcv-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-sdcv.el

(autoload 'entropy/sdcv-search-at-point-tooltip "entropy-sdcv" "\
Mainly interactive func for search point or marked region
string with sdcv cli." t)
(autoload 'entropy/sdcv-search-input-adjacent "entropy-sdcv" "\
Mainly interactive func for search with inputted querying
string with sdcv cli." t)
(autoload 'entropy/sdcv-toggle-backend "entropy-sdcv" nil t)
(register-definition-prefixes "entropy-sdcv" '("entropy/sdcv-"))


;;; Generated autoloads from entropy-sdcv-backends.el

(register-definition-prefixes "entropy-sdcv-backends" '("entropy/sdcv-backends-"))


;;; Generated autoloads from entropy-sdcv-core.el

(register-definition-prefixes "entropy-sdcv-core" '("entropy/sdcv-core-"))


;;; Generated autoloads from entropy-sdcv-show.el

(register-definition-prefixes "entropy-sdcv-show" '("entropy/sdcv-show-"))

;;; End of scraped data

(provide 'entropy-sdcv-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-sdcv-autoloads.el ends here
