\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename entropy-emacs_introduction.info
@settitle entropy emacs introduction
@documentencoding UTF-8
@documentlanguage en
@c %**end of header

@finalout
@titlepage
@title entropy emacs introduction
@author Entropy
@end titlepage

@contents

@ifnottex
@node Top
@top entropy emacs introduction

@image{../logo,,,,png}
@end ifnottex

@menu
* Preface::
* Repo folder struct::
* Main config files::
* Self built packages::
* Eemacs top-key map::
* Custom @samp{entropy-emacs}::
* Hacking for @samp{entropy-emacs}::
* Config feature specifiction introduction::
* Docs refers::

@detailmenu
--- The Detailed Node Listing ---

Config feature specifiction introduction

* Internal basic setting specific::
* Major modes for programming::
* Packages enhancements and introduction::
* Emacs on windows::

Internal basic setting specific

* Windows configuration and workspace defination::
* Modeline themes toggle::
* Chinse input method::
* Globally readonly mode::
* Org-mode::
* Miscellaneous emacs internal setting::
* Font specific::

Windows configuration and workspace defination

* Eyebrowse::
* Buffer or Window switching::

Major modes for programming

* C and C++::
* Php::
* Html and Css::
* Javascript::
* Web front-end realtime previewer::
* Python anaconda::

Packages enhancements and introduction

* Ivy and Helm::
* Emacs-W3m::
* Elfeed::
* Gnus::

Emacs on windows

* Bash and unix tool chains for windows::
* Portable emacs environment on windows::
* Notice for key touching on windows::

@end detailmenu
@end menu

@node Preface
@chapter Preface

Entropy emacs was one personal emacs config built for me at the
begining and derived from @uref{https://github.com/seagle0128/.emacs.d, centaur emacs} which was one simple pure and
with sets of mordern emacs extension tracking on.

@quotation
@samp{entropy-emacs} was based on the commit of @samp{centaur-emacs} by
@samp{55b07da55415b48ee75cde67a3f99dd80f3bb491}
@end quotation

But with the time when @samp{entropy-emacs} grown up after one year, it's
seems like it can be sharing for some newbie falling with emacs as be
aimed to brought up the easiest way of using or working based on
emacs. Along the way, I came for built it with thus on.

@node Repo folder struct
@chapter Repo folder struct

@samp{entropy-emacs} has the implicit repo dir struct as the aim for built
repo with the constant traditional repo style among with other project
dir struct used by myself.

In the root node, it be with three folder:
@enumerate
@item
org
@item
annex
@item
elements
@end enumerate

This three folder has their own meaning respectively, all of them was
created as the parts of one normal project I used, thus for:

@itemize
@item
@strong{org:} contained the all docs of this project.

@item
@strong{annex:} stored annex fragments as the stuffs be used for docs
like images or other references based on.

@item
@strong{elements:} the main elements (elements consists of
@samp{entropy-emacs}) stored location.
@end itemize


What for more?

This struct design were just use these three based rule without any of
other restriction which show that arbitray layouts adding was
permitted.

@node Main config files
@chapter Main config files

@samp{entropy-emacs} host configs file divided into three categories,
i.e. @strong{init config} and @strong{self buit pakages}.

The @samp{init config} conceptual thoughts from @samp{centaur-emacs's} design
philosophy, as it's original intention for building the simple and
pure as origin emacs like configs, in @samp{entropy-emacs}, they
abbreviated as @samp{entropy-emacs-xxx.el}. 

@samp{entropy-emacs} using the three bind-level core packages managements
design to separate individual source files in @samp{elements/core} root
path, they are the @samp{initial level}, @samp{binds-level} and the @samp{tentacle
level}, the loading sequence was followed the mentioned order.

On the startup time, fistly loading the @samp{initial-level} which try to
customizing next loading environment and inizilized some internal
requested specification, and providing the top-level apis for
subroutines. The seconed time loading the basic core functions,
internal-variables defination used for rest tentacles, so as called it
@samp{binds-level}, finally loading each entropy-emacs recipes called
@samp{tentacle-level}.

For now, the @samp{initial-level} was injected for
@samp{entropy-emaacs-defcustom.el}, and the @samp{binds-level} are hosted in
follow three files:

@enumerate
@item
@strong{The var binds}
@enumerate
@item
@samp{entropy-emacs-defvar.el}
@item
@samp{entropy-emacs-defconst.el}
@end enumerate

@item
@strong{The function binds}
@enumerate
@item
@samp{entropy-emacs-defun.el}
@item
@samp{entropy-emacs-message.el}
@end enumerate
@end enumerate

For file named convention, @samp{entropy-emacs-xxx.el} files are named with
'xxx' as the suffix for distinguishing with each other, for
convenience, suffix of them were point to their config direction
directly, such as @samp{entropy-emacs-org.el}'s suffix @samp{org} was implicit
it's the init config file for feature @samp{org-mode}, and so as on for
others init files.

There's the list of the tentacles and their description:

@multitable {aaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
@headitem @strong{Category}
@tab @strong{init package}
@tab @strong{package description}
@item 
@tab entropy-emacs-basic.el
@tab basic setting for @samp{entropy-emacs}
@item basic config
@tab entropy-emacs-ui.el
@tab ui defination with the customized startup screen design
@item 
@tab entropy-emacs-themes.el
@tab theme collections and startup default theme sets
@item 
@tab entropy-emacs-modeline.el
@tab modeline themes collection and default modeline theme setes
@item 
@tab entropy-emacs-path.el
@tab path configs for @samp{entropy-emacs} specfic environment
@item 
@tab 
@tab 
@item window conigurations
@tab entropy-emacs-wc.el
@tab The emacs window moving and workaround emulator configuration
@item 
@tab entropy-emacs-popup.el
@tab The popuped window procedure defination
@item 
@tab 
@tab 
@item 
@tab entropy-emacs-ivy.el
@tab @uref{https://github.com/abo-abo/swiper, ivy} mode configs and others refer enhancements
@item interactive chains
@tab entropy-emacs-company.el
@tab @uref{https://github.com/company-mode/company-mode, company-mode} confifs and other refer enhancements
@item 
@tab entropy-emacs-yas.el
@tab @uref{https://github.com/joaotavora/yasnippet, yasnippet for emacs} configs and other refer enhancements
@item 
@tab 
@tab 
@item 
@tab entropy-emacs-org.el
@tab emacs org mode configs
@item 
@tab entropy-emacs-markdown.el
@tab emacs markdown mode configs
@item major modes
@tab entropy-emacs-c.el
@tab C/C++ mode configs with @samp{irony} completion chians
@item 
@tab entropy-emacs-lisp.el
@tab emacs lisp mode configs
@item 
@tab entropy-emacs-web.el
@tab web mode (web front/back end) configs (inclues js css html php)
@item 
@tab entropy-emacs-python.el
@tab python mode config with @samp{company-anaconda} completion chain
@item 
@tab entropy-emacs-lua.el
@tab lua mode configs
@item 
@tab 
@tab 
@item 
@tab entropy-emacs-shell.el
@tab emacs internal shell front-end enhancements
@item tool-chains
@tab entropy-emacs-vcs.el
@tab git/svn codes version control with @samp{magit}
@item 
@tab entropy-emacs-structure.el
@tab programme editting structs fold/expanding feature package
@item 
@tab entropy-emacs-highlight.el
@tab codes snippet highlighting guide feature provider
@item 
@tab entropy-emacs-dash.el
@tab dashboard of api query prompt powerd by external tool @uref{https://github.com/zealdocs/zeal, zeal}
@item 
@tab 
@tab 
@item entertainments
@tab entropy-emacs-emms.el
@tab gnu emms as media play control panel @samp{entropy-emacs} specifics
@item 
@tab entropy-emacs-game.el
@tab emacs internal game setting config optimization
@item 
@tab 
@tab 
@item fundamental
@tab entropy-emacs-package.el
@tab on-line packages mirror management and local featuere loaded configs
@item 
@tab entropy-emacs-custom.el
@tab custom file loading setting with alternative custom file specific
@item 
@tab 
@tab 
@item code server
@tab entropy-emacs-coworker.el
@tab third-party language server query insall library.
@item 
@tab entropy-emacs-codeserver.el
@tab the dashboard for language server installer
@end multitable

@node Self built packages
@chapter Self built packages

As the default, elpa packages was enough for users to use emacs with
extensions comfortably, but some kinds of demands for who want working
something else with emacs as well must doing as them self, this the
reason for me to build things just I using or just contained within
@samp{entropy-emacs}.

Pacakges I built was aimed for:
@itemize
@item
Enhancing the basic emacs function or other elpa packages.
@item
Things needed for me as the special hobby.
@item
Useful self built extension which hope to sharing with others.
@end itemize


Now, I built serveral packages shown as below table:

@multitable {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
@headitem package name
@tab pakage description
@item entropy-cn-dict
@tab point char or region translation for chinese words (also useful for traditional chinese)
@item entropy-sdcv
@tab the emacs multi-dictionaries framework
@item entropy-common-library
@tab librarys for building other @samp{entropy-emacs} package
@item entropy-project-manager
@tab simple project managements system
@item entropy-counsel-stuffs
@tab stuffs managemetns as notes, bookmarks recording or modifying chain
@item entropy-dired-cp-or-mv
@tab dired copy or move files extension for enhancing based dired refer function
@item entropy-epub2org
@tab convert epub ebook into org-mode files format front-end
@item entropy-global-read-only-mode
@tab emacs globally readonly mode for forcing lock buffer while opening
@item entropy-open-with
@tab open files using external applications
@item entropy-org-batch-refile
@tab batch refiling entries from org buffer
@item entropy-org-export-theme-toggle
@tab toggle org html export theme specific for choosing theme or buiding it temporally quickly
@item entropy-org-widget
@tab useful org widgets for other org refer extension building
@item entropy-portableapps
@tab emacs @uref{https://portableapps.com/, portableapps query} and open front-end for windows plattform
@item entrop-proxy-url
@tab http retrieving proxy tool for eww and emacs-w3m
@item entropy-s2t
@tab convert simplified chinese to traditional chinese func used for @uref{https://github.com/tumashu/pyim, pyim} (emacs chinese input method)
@item entropy-unfill
@tab unfill buffer paragraph with specific rules built by user self
@item entropy-shellpop
@tab the yet-another @uref{http://github.com/kyagi/shell-pop-el, shell-pop} toolkit replacement for using @uref{https://github.com/wasamasa/shackle, shackle} as the popup method
@end multitable

@node Eemacs top-key map
@chapter Eemacs top-key map

For unified emacs experience both of CLI and GUI, @samp{entropy-emacs}
using the auto-adaptable key @samp{entropy/emacs-top-key} as the the
unified prefix key to bind a keymap @samp{entropy/emacs-top-keymap},
various commands hosted on it to be interactived thus.

Commonly @samp{entropy/emacs-top-key} was bind to @samp{C-@@} in CLI and @samp{C-`} in
GUI, all of them are reflected with physical key hints @samp{C-`} on your
keyboard. We make the convention that string @samp{[eprefix]} indicate the
hint @samp{entropy/emacs-top-key} , that example @samp{[eprefix] w} means hint
@samp{entropy/emacs-top-key} and @samp{w} sequentially.

@node Custom @samp{entropy-emacs}
@chapter Custom @samp{entropy-emacs}

@samp{entropy-emacs} has lots of custom-variables be defined
acquiescently. For each feature in main config files
@samp{entropy-emacs-xxx.el} or in self built extensions, @samp{entropy-emacs}
custom-variables provides the wild freedom customized ability to
specific config actually to referred using experience.

Since emacs using @samp{custom.el} for stored all customized setting
temporarily entries, @samp{entropy-emacs} also allow user to setting custom
variable of @samp{entropy-emacs} to that place and this is the default
order.

When the first time you using @samp{entropy-emacs}, you may want to create
the @samp{custom.el} file in root of @samp{entropy-emacs} used by emacs initial
with, as the well, @samp{entropy-emacs} gives the template custom file
located in same place which named @samp{custom-example.el}, you can copy it
as custom file for convenience.

@node Hacking for @samp{entropy-emacs}
@chapter Hacking for @samp{entropy-emacs}

@samp{entropy-emacs} allow user to modified internal config files but this
is not suggested by. Sets of @samp{entrop-emacs} was corresponding to each
other frequencly which shown as that if you modified one code snippet
while you are not familiar with details logic designation of
@samp{entropy-emacs}, you will get mess with the functional in some place.

But, if you want to hacking for some code snippet you can adding
@samp{advice} for them and stored in your own config
folder. @samp{entropy-emacs} providing one navigation detector feature for
loading you own config files, this extern config loading detector was
@samp{elisp} func which stored in @samp{CUSTOM-DIY.el} under root of
@samp{entropy-emacs}, this file were not exist by default, you should
create it by yourself.

@samp{CUSTOM-DIY.el} can be stored elisp codes arbitrarily, which means
that you could write the func modifiction all adding new config
features in that file, but the recommended way for using this file was
stored the extern config files load function to it, i.e. some thing
like below:
@lisp
;; load "my_entropy-emacs_extern.el" after loading "custom.el" .
(let ((file (file-exists-p "/xxx/xxxx/.../my_entropy-emacs_extern.el")))
  (when (file-exists-p file)
    (load-file file)))
@end lisp


Thus, the file @samp{my_entropy-emacs_extern.el} will be loaded after emacs
custom file loaded, that as the same step before other @samp{entropy-emacs}
files be interpreted.

The conceptual for thus, file @samp{my_entropy-emacs_extern.el} can be
secondary @samp{init.el} or the secodary emacs config repo main thing.

@node Config feature specifiction introduction
@chapter Config feature specifiction introduction

This chapter introducts the main config features of @samp{entropy-emacs},
each part of below sections pointing one feature category which was
the collection sets description and feature specified core sets, you
may want to select refer things you'd metioned or care about for
jumping with the sequence as the section it self, but I recommended
for reading sections one by one instead of jumping where while you are
fisrt using @samp{entropy-emacs}.

Each feature required the basic emacs using experience for or has
been, which means if you are the newbie of emacs, you must reading the
emacs internal tutorial first and then doing thus.

For WINDOWS specification section, only suggested reading task for
someone using emacs on windows, that section was the sets of
experiences by me as using emacs on windows, I often using emacs on
WINDOWS as one portable programming encapsulation environment, that
portable work-around for daily using of me.

For chinese emacs user, when you want to input chinese and showing CJK
fonts well (without lagging or other crash problem as emacs with cjk
status), you can obtain the minor skills from 'Font specific' section.

Latest, all of below section can be the taste of @samp{entropy-emacs} for
understanding the difference between this to the default emacs using
sensing, happy hacking with @samp{entropy-emacs}.

@menu
* Internal basic setting specific::
* Major modes for programming::
* Packages enhancements and introduction::
* Emacs on windows::
@end menu

@node Internal basic setting specific
@section Internal basic setting specific

@samp{entropy-emacs} using elpa/melpa emacs extension to build basic
work-around, for enhancing the basic emacs using experience.

Basic config of @samp{entropy-emacs} can be splitting into seven nodes:
@itemize
@item
workspace
@item
modeline specific
@item
global buffer lock 
@item
input method of chinese refer
@item
org mode
@item
font specific
@item
miscellaneous config
@end itemize

All of these seven parts consists the basic core of @samp{entropy-emacs}
config. They are oriented respectively for their individual direction,
and was necessary be the part of core of this.

@menu
* Windows configuration and workspace defination::
* Modeline themes toggle::
* Chinse input method::
* Globally readonly mode::
* Org-mode::
* Miscellaneous emacs internal setting::
* Font specific::
@end menu

@node Windows configuration and workspace defination
@subsection Windows configuration and workspace defination

Emacs using @strong{buffer}, @strong{window}, @strong{frame} to recoganize the current
editting space and recorde it's state, it's the basic func for elisp
programmer for built editting space extension for as more convenience
to create, move, toggle each layouts editting space, we call 'editting
sapce' as @strong{workspace}.

Workspace managements consists of two parts:
@enumerate
@item
layout toggle
@item
window toggle
@end enumerate

A workspace was one layout consists with several windows internal of
it, thus layout toggle can be used with different workspace switching
or creating sets of workspace who have different working purpose. This
is useful for who doing different thing at the same time or as the
relaxing and working state toggle button during the day.

Thus, as the layout toggle, the basic thing as you facing to emac
using was to chaning the cusor point with sets of buffers, as buffer
stored in window, cusor switching upon different buffers on the
different windows was called window toggle.

@menu
* Eyebrowse::
* Buffer or Window switching::
@end menu

@node Eyebrowse
@subsubsection Eyebrowse

@samp{entropy-emacs} workspace creating, toggle, and defination using
@samp{eyebrowse} melpa extension, it is settle out with solid done. You can
find it on @uref{https://github.com/wasamasa/eyebrowse, github}.

In @samp{entropy-emacs}, @samp{eyebrowse} was acted as the workspace management
host which provide layout toggle, creating, renaming or deletion
functions. Each workspace's name, window configuration, slot number
was stored as the sets of @samp{frame-parameter}, so it works well with
other emacs intern toolchain.

@itemize
@item
@strong{eyebrowse's workspace dash list:} 

@enumerate
@item
@samp{tag}: indicated layout defination name.
@item
@samp{slot}: the numberic identification of respective layouts
@end enumerate

Which means shown above, eyebrowse exhibits each workspace through
the way for display the layout tag-name and it's numberic slot.

In @samp{entropy-emacs} , the tag-name and slot number was displayed on
the left of modeline which like as:

Commonly, the display format of thus was formula as
@code{slot-number:tag-name}, and the face was usually came as yellow
forground covered on black background.

Layout switching was through the way of query prompt within
minibuffer and enhanced with candidates showing list powered by @uref{https://github.com/abo-abo/swiper, ivy},
each candidate was one unique slot number with workspace name:

@example
+--------------------------------------------------------------------------------+
|  * 169 U(Unix) *scratch*      Lisp Interactioin Orgstruct>>      << 4: 23 ALL  |
+--------------------------------------------------------------------------------+
(1/3) Enter slot:

     +------------------+
---> |1: basic workspace|
     +------------------+
      2: Readme edit
      3: News reader
@end example

But the easist way for doing like this was using the shortcuts
prefix @samp{[eprefix] w} with the workspace slots number
limited within decimal based digit as '1~9', thus if you active key
stick @samp{[eprefix] w 2} , you will toggle workspace to slot
'2'. By default, @samp{eyerbrowse} supports toggle to none exists slot
which creates it while then but without tag inputting prompt, or you
can create new slot by sticking @samp{[eprefix] w C-c} which
will create one new slot with tag inputting demands prompting hacked
adding by @samp{entropy-emacs}.

@item
@strong{Derived workspace:}

By default each workspace provided by eyerbowse layout managements
was independently by each other on the conceptual aspect, which
means that eyerbowse recognizes layouts by one-dimension that
[1,2,3,4,@dots{}] one by one without any sub-group concept.

In many cases if your workspace was too complicated as what that
sets of buffer opened in your single screen hardware actually, this
will cause the disaster for your eye-visual focus moving and
laggning the way when be with your poor eyesight.(also seen as your
screen was low dimessions as traditional '1366x768'.)

@example


+---------------+-------+--------------------------+
|               |       |                          |
|   buffer 0    |buffer |     buffer 5             |
|               |       |                          |
+---------------+  4    +------------+-------------+
|               |       |            |             |
|   buffer 1    |       |            |  buffer 7   |
+------+--------+       |buffer 6    |             |
|      |        |       |            |             |
|      |        +-------+------------+-------------+
|      |        |                                  |
|buffer| buffer |  xxxxx xxx xxx xxx               |
|      |        |                                  |
|  3   |   2    |     xxx xxx xxx xxx              |
|      |        |                                  |
|      |        |                                  |
|      |        |                                  |
|      |        |                                  |
|      |        |                           buffer8|
+------+--------+----------------------------------+


@end example

Do you worried about this single screen layout measured your mind?

Or you can create one new workspace to exchange partitial of current
state to that new slot, but how you organize the association between
these two slots? By memory of your mind?  God bless, it's just
compat for that state where you just have one slot doing as this, if
further @dots{} how imagination what will happening?

For resolving this problem, @samp{entropy-emacs} expands eyebrowse
one-dimension workspace management logic to @strong{main-derived}
conceptual. For the literally meaning , workspace has two kinds:
@itemize
@item
@strong{main slot}
@item
@strong{derived slot}
@end itemize

Main slot can be understanding as the origin one while slot has been
created, in that case you haven't given the try or have demands for
several buffer splitted in one screen which will cause occurance as
above description. Derived slot will be created when you doing for
arbitray reason for that.

@example

+------------+ +------------+ +------------+
| main slot 1| | main slot 2| |main slot 3 |
+-----+------+ +-----+------+ +------+-----+
      |              |               |
       \             |               |
+------v-----+ +-----v------+ +------v-----+
|            | |            | |            |
| derived 1  | | derived  1 | | derived  1 |
|            | |            | |            |
|         2  | |          2 | |          2 |
|            | |            | |            |
|         3  | |          3 | |          3 |
|     .      | |            | |            |
|     .      | +------------+ |          4 |
|     .      |                |            |
|     .      |                |          5 |
|            |                |            |
| derived 9  |                +------------+
|            |
+------------+

@end example

@item
@strong{Derived slot create:}

To create one derived slot can be implemented as call func
@samp{entropy/emacs-basic-eyebrowse-create-derived} or with it's
keybinding @samp{C-c v}, after then, you will be required to create the
derived workspace tag name and the last you will get the workspace
as displayed with slot and tag name format as

@example
main-slot.derived_number:⛓main-slot:"main workspace tagname"☛derived name
@end example

Above demos show the face and the instant display format of derived
slot derived from the main slot '1:temp'.

For toggle the derived slot, keybinding @samp{C-c M-v} as so.

For backing to main slot, was hanged with keybinding @samp{[eprefix] w
  C-o} which call function @samp{entropy/emacs-basic-eyebrowse-switch-top},
it's useful for quicly back from the temp derived slot to top
(called 'top' by main) slot without remember the current main slot
number or backing with calling
@samp{entropy/emacs-basic-eyebrowse-switch-basic-window}.

@item
@strong{Derived slot limitation:}

Now, for the designation purpose, @samp{entropy-emacs} just giving each
main slot nine derived slots for deriving by, this because of that
each derived slot was numberic as the one digit float number, it's
hard to expand more with thus with float number floor sorting func
designing.

For using case, 9 derived workspaces was enough for what I may
thought, it's no reason to build various of derived one which will
cause the difficulties managements, for what as known:
@quotation
less is more
         ---- xxxx
@end quotation
@end itemize

@node Buffer or Window switching
@subsubsection Buffer or Window switching

The conceptual of window configuration under the workspace was buffer
and window switching , thought about the scene that if you want to
jumping with several buffer or window internal of one workspace, the
way for solving that problem was what it is.

@samp{entropy-emacs} three ways for filling this conceptual:
@enumerate
@item
buffer jumping
@item
window exchange
@item
window size adjusting
@end enumerate


@itemize
@item
@strong{Frame place jumping:}@*
@example

+-------------+-----------------------------+
|             |                             |
|  buffer 1   |                             |
|             |                             |
+-------------+      buffer 3               |
|             |                             |
|             |                             |
|  buffer 2   |                             |
|             +-----------------------------+
|             |                             |
|             |                             |
|             |     buffer 4    <--- current|
|             |                             |
+-------------+-----------------------------+
@end example

Assumption on example emacs frame demo, your cursor are on buffer-4
currently and the place you want to jumping to was buffer-1. If you
use emacs internal primitive func @samp{other-window} , it's hard to do
as buffers counts larger than 2.

@samp{entropy-emacs} using melpa package @samp{window-number} for enhance it
be as the morden query prompt for all buffers in current frame
state, it using func @code{(window-number-switch)} for be the subtitude
to func @code{(other-window)} emacs internal default window switching
func.

It stick window number on modeline, and binding func
@code{(window-number-switch)} to the origin keybinding for
@code{(other-window)} as @samp{C-x o}, if window sibling as above frame
session example, it will query prompt for choose window with
candidates shown listed in minibuffer, which provide you the ability
to selected window number by input window number directly or with
the selecting up and down within the candidates list.

Another bennifit window jumping method was using us self-built func:

@example
entropy/emacs-basic-windmove-(up/down/right/left)-cycle
@end example

The raw func obtained from
@uref{https://github.com/troydm/emacs-stuff/blob/master/windcycle.el}.

They binding to @samp{C-x up/down/right/left}. That means you could
jumping cycle round for sibling window quickly with your instincts
visual sensitive.

@item
@strong{Window resize:}

By the default, any dividing behaviour in emacs was width 'half'
sibling state, but the occurence when you want to get the specififc
window dividing width, may rely on the external extension power.

@samp{entropy-emacs} use package @samp{winresize} to provide such feature. And
it's main func binded with @samp{C-<f10>} shortcut, in that way, when you
active it til you enter the @samp{RET} key, the full duration process was
using Arrow-key to resize window size animatedly as the visualized
size alteration.

Arrow-key up, down, left and right controlling windows size rising
or shutter forms. For just two window of one frame horizontally,
right and left arrow-key was only functional, the otherwise for just
two as it but with vertically state was limited to just up and down
keys functional, excepting this, opposite conceptual.

Once you enter @samp{RET} after resizing, the new window size state
stored as the result, this size will remained by @samp{eyebrowse} and
other workspace refer toggle or restore units.

@item
@strong{Window exchanging:}

With eachs window stick square on the fixed position when setted
down by dividing for, the occurence for exchanging window buffer was
frequently, emacs internal func @code{buf-move-up/down/right/left} gives
the try as thus. We binding them to @samp{C-c C-up/down/right/left}
respectively.
@end itemize

@node Modeline themes toggle
@subsection Modeline themes toggle

@samp{entropy-emacs} provide four kinds modeline style:

@multitable {aaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}
@headitem name
@tab tag
@tab description
@item origin-specific
@tab origin
@tab minor extended origin `mode-line-format`
@item doom-modeline
@tab doom
@tab morden simply mode-line style extracted from @uref{https://github.com/hlissner/doom-emacs, doom-emacs}
@item sapceline
@tab spaceline
@tab morden extensible mode-line style of @uref{https://www.spacemacs.org/, spacemacs}
@item spaceline-icons
@tab spaceline-icons
@tab @uref{https://github.com/domtronn/all-the-icons.el, all-the-icons} patched @samp{spaceline}
@item powerline
@tab powerline
@tab the enhanced exensible mordern mode-line based used for @samp{spaceline}
@end multitable


Each of them are combined specific for be fit for @samp{entropy-emacs}. You
can set the custom-variable @samp{entropy/emacs-modeline-style} with the
tag symbole shown from above table:
@lisp
;; demo modeline setting code snippets of entropy-emacs
(setq entropy/emacs-modeline-style 'powerline)
(setq entropy/emacs-modeline-style 'spaceline)
;; .... and so on
@end lisp

The default modeline style are 'doom-modeline' and 'origin', which has
been initialed with eyebrowse workspace indication segment built with
derived logic widget(see @ref{Eyebrowse, , entropy-emacs eyebrowse introduction}). These
default setting was aimed with keeping balance with emacs performance
and visualization experience.

Spaceline (or xxx-icons) was the wild used modeline of other users's
custom emacs config, but in @samp{entropy-emacs}, it is not recommended for
using this as the default modeline style, because it lagging with huge
process garbage collection idle slate during commonly emacs using
occurence. This was caused by sets of segments of spaceline for what
was lead to this issue. Another icons version spaceline was not
recommendation for as, the font default required for and the based
spaceline core performance problem was both annoying for user who want
to use them out of box. (@samp{spaceline-icons} will not renderd nice on
windows platform as well as linix platform even if the extra fonts it
required were installed corrently).

Thus, if you want to use spaceline, I recommend to use powerline
instead because spaceline was extension from it and powerline origin
segment corresponding was pure and simple which may be without lagging
performance as what gets into spaceline.

the Toggle func for switching different modeline at real time was
supported with bounds of func:
@itemize
@item
@samp{entropy/emacs-modeline-mdl-origin} :@*
Toggle to origin-specific modeline style.
@item
@samp{entropy/emacs-modeline-mdl-doom} :@*
Toggle to doom modeline style.
@item
@samp{entropy/emacs-modeline-mdl-powerline} :@*
Toggle to powerline modeline style.
@item
@samp{entropy/emacs-modeline-mdl-spaceline} :@*
Toggle to spaceline modeline style.
@item
@samp{entropy/emacs-modeline-mdl-spaceline-all-the-icons} :@*
Toggle to spaceline-all-the-icons modeline style.
@end itemize


By defualt modeline style toggle funcs was all disabled unless you set
custom-variable @samp{entropy/emacs-enable-modeline-toggle} to 't'. And for
specific emacs version, @samp{entropy-emacs} gives different modeline style
pre setting;
@itemize
@item
emacs version @samp{25.2.1} : doom
@item
emacs version @samp{25.3.1} : origin
@item
emacs version @samp{26.1} and above: doom
@end itemize

This specification was rely on the unicode font render effection
activation reason that @samp{25.3.1} version was specially not support as
what, so as it.

@node Chinse input method
@subsection Chinse input method

For emacs inputing with CJK chars experience, the default chosen for
you was to used system default input tool-chain which was external out
of emacs's controlling. And then the second for that was to using the
emacs interanl chinese input methods as the list below:

@itemize
@item
@samp{chinese-4corner}
@item
@samp{chinese-array30}
@item
@samp{chinese-b5-quick}
@item
@samp{chinese-b5-tsangchi}
@item
@samp{chinese-ccdospy}
@item
@samp{chinese-cns-quick}
@item
@samp{chinese-cns-tsangchi}
@item
@samp{chinese-ctlau}
@item
@samp{chinese-ctlaub}
@item
@samp{chinese-ecdict}
@item
@samp{chinese-etzy}
@item
@samp{chinese-punct}
@item
@samp{chinese-punct-b5}
@item
@samp{chinese-py}
@item
@samp{chinese-py-b5}
@item
@samp{chinese-py-punct}
@item
@samp{chinese-py-punct-b5}
@item
@samp{chinese-qj}
@item
@samp{chinese-qj-b5}
@item
@samp{chinese-sisheng}
@item
@samp{chinese-sw}
@item
@samp{chinese-tonepy}
@item
@samp{chinese-tonepy-punct}
@item
@samp{chinese-ziranma}
@item
@samp{chinese-zozy}
@end itemize

You don't have to know the each knowledge about them, but the most pop
used one was @samp{chinese-py} which was aslo the most popular method for
chinese people for using as the default chinese hans char input
method.

Although @samp{chinese-py} input method was pure and powerful for basic
using, if onece you get it on your scatter doing, you will find it was
really simple and crude which can not be used as the daily tool for
thus. As the result, @samp{entropy-emacs} usig the most powerful and
comprehensive 'pinyin' function built melpa extentioin @uref{https://github.com/tumashu/pyim, pyim} :

@example
  这是一段中文说明，你好shijie
                        ^
                        |
                        +-------------------------+
                        | 1. 世界 2. 时节 .....   |
                        +-------------------------+
@end example

Above demo shows the fully process for input chinese using
pyim. pinyin candidates shown within the tooltip widget @samp{posframe}
created by the author same as pyim be, there's other candidates
widgets for chosen:
@enumerate
@item
minibuffer

Using minibuffer be the widget as:
@example
+----------------------------+
|                            |
| xxx|                       |
|                            |                                        
|                            |                                        
|                            |                                        
|----------------------------|                                        
| 1.word1 2.word2 .......   <------minibuffer pyim pinyin candidate list
+----------------------------+
@end example

@item
popup:

Similarity with posframe but using old emacs buffer frame api which
may lagging of performance that based with it's design logical, as
the opposite, @samp{posframe} using the new @samp{child-frame} emacs feature
which just contained in emacs version on 26.1 and above.

So as that, @samp{entropy-emacs} using 'popup' to pyim config for emacs
version below 26.1 and the oppsite using 'posframe'.
@end enumerate


@itemize
@item
@strong{Pyim dicts:} @anchor{org81b2ade}

Although @samp{pyim} was one emacs extension written by @uref{(info%20"elisp"), elisp}, it was
also one comprehensive chinese input programe which as the same sets
of products rely on operation system e.g. @samp{fcitx-pinyin}, @samp{rime} or
@samp{ibus-pinyin}, it relies on emacs internal input method frame work
the comprehensive input frame work built with emacs. Thus pyim need
extra char dicts for driven for candidates completion.

@samp{pyim} extra dict was plain text format as:
@example
ni-hao 你好
shi-jie 世界
@end example

Sequence continuing as thus.

@samp{entropy-emacs} provide the default extra dicts archived in @uref{https://sourceforge.net/projects/entropy-emax64/files/entropy-emacs_hitch/20190505/, here},
there's two dicts:
@enumerate
@item
core.pyim
@item
extra.pyim
@end enumerate

Each of them are extract from other open source permitted input
method, as you do not worry about the copyright with legal
complication.

There two dicts was enough for daily using as well as me, names of
them are meaned as the loading sequence or dict collection
categories belong to them individually. @samp{Core.pyim} was extract from
rime's internal dict, containes 816321 entries, reached the normal
proper dicts size as suggested from pyim author, @samp{extra.pyim} was
the collection from several none copyright obselete dicts, it
contained extra popular vocabularies and animal, stars, psycology or
other sets of scienece subjects vocabulary collection, it's size
about 0.8 million entries.

@item
@strong{using liberime as rime backend for pyim}

Except for plain text dictionary as cacheing method, the another
project @uref{https://github.com/merrickluo/liberime, liberime-config} gives the ability to get IME query
candicates from native @uref{https://rime.im, rime} engine @uref{https://github.com/rime/librime, librime}, and the configuration
steps are easily and thus as:

@enumerate
@item
given the rime schemes host in operation system for variable
@samp{entropy/emacs-pyim-liberime-scheme-data}.
@item
Setting the specific rime scheme selected 
@item
Optionally give the rime cache dir value to
@samp{entropy/emacs-pyim-liberime-cache-dir}.
@end enumerate

@item
@strong{enable pyim with @samp{entropy-emacs}:}

The turn-off custom variable controlling whether enable pyim when
emacs startup finished i.e. @samp{entropy/emacs-enable-pyim}, you can
active it in your @samp{custom.el} file, then the next time you start up
or open new session of emacs , pyim will automatically startup using
the default dicts specific by @samp{entropy-emacs} as introduction form
@ref{org81b2ade, , pyim dicts section}, or if you want to enable dicts specified by
yourself, you can setting up custom-variable
@samp{entropy/emacs-pyim-dicts}, the variable information and value
format can be shown by touching @samp{C-h v entropy/emacs-pyim-dicts
  RET}.

@item
@strong{pyim conversion between simple chinese with traditional chinese:}

Chinese hans char has been redesigned for simplification for daily
using in CHINA, but be remained the old version shape of char for
people in CHINA taiwan province and HongKong or others chinese
language based countries. As for the first char shape named @samp{simple
  chinese} and the rest was called as @samp{traditional chinese}.

@samp{entropy-emacs} supported both of them for inputting choice, but
initial based inputting was @samp{simple chinese}, you can call func
@code{(entropy/emacs-basic-toggle-pyim-s2t)} to toggle it to
@samp{traditional-chinese} as the final presentation on screen.

@quotation
Original pyim not support the feature of conversation between
them, but it provide one feature @samp{pyim-magic-converter} whose
description as below:

> 将 “待选词条” 在 “上屏” 之前自动转换为其他字符串. 这个功能可以
实现“简转繁”，“输入中文得到英文”之类的功能。

@samp{entropy-emacs} create the self func
@samp{entropy/emacs-basic-toggle-pyim-s2t} for using this detector
feature for reaching the aim of thus.  This core was provided by
package @uref{https://github.com/c0001/entropy-s2t, entropy-s2t} which list the hash table @samp{entropy/s2t-table}
pointed each simple chinese char to the corresponding traditional
chinese char.

So as on the inputting prompt candidates will still be the
simple chinese char shape style.
@end quotation

@item
@strong{Half or full width punctuation:}

Pyim allows user to toggle punctuation standard widths withs both of
@samp{half} and @samp{full} style with keybinding @samp{C-1} while you are in pyim
input session, this may be useful when you are editting the list or
table in org mode.
@end itemize

@node Globally readonly mode
@subsection Globally readonly mode

Emacs open all common buffers with editted state by default all. It be
convenience with the state for usually sights which allow user to
quickly read or write sth into file.

But with the buffer counts increasing for one emacs sessin, this
feature was annoying with the worriers for that we can not keep
careful for all buffers modification state when you take the mistake
modification little bit inadvertently.

The way for solving this problem is to create one feature for emacs to
lock all buffer as read-only (i.e. locked) state by the default for
buffer opening, because most of occurrence we open one file is to read
but not to write.

@samp{entropy-emacs}'s self built extension @uref{https://github.com/c0001/entropy-global-read-only-mode, global-readonly-mode} give the
anwser.

@samp{global-readonly-mode} provide three modes:

@multitable {aaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaa}
@headitem type modes name
@tab value
@item find-file initial
@tab all
@item major modes rule
@tab modes
@item dired find-file initial
@tab convert
@end multitable

You will enable it do with filling follow elisp codes snippet into
custom file:
@lisp
(setq entropy/grom-enable t)
(setq entropy/grom-readonly-type "all")
@end lisp

The suggested mode choice was @samp{all}, which injecting read-only feature
into @code{(find-file)} function, after sets this value, any buffer opened
with lock state excluding the buffer name exception list
@samp{entropy/grom-find-file-except-bfregexp-list}, the value of this list
was regexp string matched before @code{find-file} opens file.  Til now this
list shown as blow:
@lisp
'("autoloads\\.el"
  "\\*Compile-.*\\*"
  "loaddefs\\.el"
  "COMMIT_EDITMSG"
  "_archive"
  "^ *\\*.*?\\* *$")
@end lisp

Regexp strings contained intern of it now excepting package compliging
refer file or buffer, magit committing buffer, buffer name paired with
@samp{*} (special buffer) and some miscellaneous nameing rule buffer.

Due to the mechanism of emacs defualt setting used by other extension
built intern or from melpa/elpa, global-readonly-mode will cause some
coordination problem with other package extension function call,
because by the default some func doesn't judge the buffer read only
state before executing processing, in other words, they does with the
buffer state by editted default and only to as. Org-mode was the
typically one who required the refer buffers it will be did with must
be editted state, in which case, @samp{entropy-emacs} adding sets of
advicing funcs for the Org-mode widgets and modified with redefined
some apis for patching with adding buffer read only state detecting
snippet. The patching for Org-mode districts are:

@enumerate
@item
org agenda
@item
org capture
@end enumerate


Agenda buffer's func offering: note-add, task todo state changing, all
need to patched before func process proceeding, @samp{entropy-emacs} using
adviced func @code{(entropy/grom-agenda-unlock-current-entry)} for
enhancing the each agenda entry behaviour with global-readonly-mode
for be the advice before @code{org-agenda-add-note} , @code{org-add-log-note} ,
@code{org-store-log-note}. @samp{entropy-emacs} also create the manully func
@code{entropy/grom-unlock-agenda-files} to unlock all agenda files defined
in custom variable @samp{org-agenda-files} which be opened with, if you
want to do so , calling it.

Capture patching redefining func @code{org-capture-place-template} and the
Org-mode internal unit @code{org-datetree--find-create}, both patching for
them are minor just with adding @code{(read-only-mode 0)} to the key coding
region.

Rest modes of global-readonly-mode was the optionally not suggested
for who are having the perfects thoughts for this, if you are just one
to make the buffer open limitation while using dired open or major
modes specifiction type, try them, dired refer was forcing withou any
custom variable setting, for major modes specification, custom
variable @samp{entropy/grom-mode-list} are the motorized key for thus, you
can check it with @samp{C-h v entropy/grom-mode-list} for see the default
major modes be locked with.

Remeber, you can cancel or disable global-readonly-mode whenever you
want to do so with interactive func @samp{entropy-grom-mode} , it will
remove all the hook and cancel all the advising hooks for feature
refer when done of calling for it, oppiste as it will enable
gloal-readonly-mode again.

@node Org-mode
@subsection Org-mode

Org mode was the structor plain text doc type combined with emacs
closely, which obtained the admiration with various emacs user. This
section was implicitly for the user who understand with the basic
Org-mode knowledgebase and had used it for a while, and rest
introduction was the specification of @samp{entropy-emacs}'s Org-mode
config for kinds of aspects of it.

@itemize
@item
@strong{Item bullets style:}

Each headline in Org-mode doc with the defautl visual style inserts
with dozen of @samp{*} chars. special tyle support can be hacks for
adding. Emacs melpa package @uref{https://github.com/sabof/org-bullets, org-bullets} provides such the feature
like as but have've been stopped maintained for about 5 years. But
no matter the way thus, it's core mechnism was solid and has enough
flexibility for keeping track with new emacs version for the
furtuer.

@samp{entropy-emacs} using @samp{org-bullets} for fancying up org item bullets
style upon for creating two style:
@enumerate
@item
roman
@item
circle numberic
@end enumerate

Both of them displayed for showing the sequence number refer the
heading level instead of the asterisk counts visualized.

@samp{roman} type displayed as the sequence list as:
@example
"●" "Ⅱ" "Ⅲ" "Ⅳ" "Ⅴ" "Ⅵ" "Ⅶ" "Ⅷ" "Ⅸ" "Ⅹ" "Ⅺ" "Ⅻ"
@end example

The instance for this is:
@example
● heading 1
  Ⅱ heading 2
    Ⅲ heading 3
      Ⅳ heading 4
        Ⅴ heading 5
          Ⅵ heading 6
          ......

@end example

Same sytle show for circle numberic:
@example
"⓪" "①" "②" "③" "④" "⑤" "⑥" "⑦"
"⑧" "⑨" "⑩" "⑪" "⑫" "⑬" "⑭" "⑮"
"⑯" "⑰" "⑱" "⑲" "⑳"
@end example

Bullets shown style was the minor fancy setup, choosing the taste as
your way. follow config codes snippet for doing thus:
@lisp
(setq entropy/emacs-org-bullets-type "roman") ; or with "circle numberic"
@end lisp

@item
@strong{Headline level face:}

Headline level influenced headline face of Org-mode visulized style
corresponding each emacs theme specification. Some customized theme
package from melpa given the try to enlarge the heading font size by
default as shown with the sensible heading level case.

In @samp{entropy-emacs}, this feature was all being disabled for the
habits for me. Enlarge heading font will cause headline tag can not
be alignment with the default tag alignment setting by custom
variable @samp{org-tags-column}, this specification influenced by
@samp{entropy-emacs} specific function
@code{entropy/emacs-adjust-org-heading-scale} which be added into hook
@samp{org-mode-hook}, if you want to cancel this specification, you could
place follow codes snippet into your custom file"

@lisp
(setq entropy/emacs-disable-org-heading-scale nil)

;; Reload major-mode for current to trigger the hook 
(funcall major-mode)
@end lisp

@item
@strong{Org file open associate application:}

Org mode have the function for open link in a buffer with 'org-mode'
major mode, each file were recognized for their file type judged by
it's file name suffix e.g. ("\\.pdf", "\\.docx", "\\.cpp"). In org
mode, file identifier can be more than the file name suffis rule
recognizing, custom variabl @samp{org-file-apps} controlling thus.

In @samp{entropy-emacs}, the value of @samp{org-file-apps} was minor setting
with few entries be pdf and gif files.

Gif files was the animation picture foramt for web or local state,
it can be containd dozen frames (animation stacks) which can be the
size cover 'kb' to 'Mb'. However, when the size larger than several
'Mb', emacs will lagging seriously for a long time to display the
animation before analyzing it's fram counts, because emacs display
gif files through the way splitting the picture into the frame list
and then render them one by one, this was low effective compared
with other picture viewers. Therefore, @samp{entropy-emacs} set all the
gif file links of org file to be opened with external system picture
viewer.

Pdf file render for emacs was frame stacks in turn as the way for
display gifs, thus viewing pdf within emacs was not a good idea,
thus using system application referred it as well.

@item
@strong{Org html exporting style:}

Org has the translator backend for html exporting with the internal
default css style decoration. The defautl html page decoration was
plain and pure sytle based on web standards rule. For given sets of
html exporting style choices, Org exposed the api @samp{org-html-style}
custom variable for users to specific the external css or override
the default sets.

@samp{entropy-emacs} comes with the self built packge
@samp{entropy-org-export-theme-toggle} for providing the theme toggle
quickly way so. Although this self package was not indicated just
for org html exporting style toggle functional but also for latex
and other org exporting backends using, as now [2018-11-24 Sat
19:58:26] I just implemented the way for html exports backend.

@samp{entropy-org-export-theme-toggle} gives the four internal html
exporting themes i.e. @samp{Worg}, @samp{read-the-org}, @samp{Bigblow}, and
@samp{red-snapper}. First three are collected form other's customize org
html exports style and the last was designed by me for be the
default org html exporting style as for the furture.

@item
@strong{Org bables comfirmation:}

As well known that org mode was designed for literally programming
suits, code block embedded within the doc was merited as thus, in
org mode, that's code blocks called bable, as the broken for god's
dividing language curse for preventing humans' intention of building
the bable through across the sky.  Thus org bable to do so.

Each bable block identified with one programming language source
viewer, as thus, evaluation for codes was demands for insert the
code snippet result into context of doc currents.

By defaults, org-mode will confirm the operation decision before
evaluating them, as well in exporting status. But in org version
upon 9.1.xx, org changes it's exporting bable evaluation confirm
mechanism, which just confirm the bable evaluating when it's code
block indicated that this block's evaluating will be confirmed.

As thus, @samp{entropy-emacs} gives the try for patching the export funcs
for obtaining the origin confirmation process during the babel
evaluating. Function @code{org-babel-confirm-evaluate} was the main point
for patching with, @samp{entropy-emacs} forcing setting the local
variable @samp{org-confirm-babel-evaluate} to t in the process of this
func, because that in state of export this variable will cleaned to
null before calling @code{org-babel-confirm-evaluate} without finding the
mechanism for.

There's also the problem occured on evaluate inline abbreviated code
snippet like point on @samp{call_func()}. The issue was that the
confirmation prompt string doesn't include the babel name. For
resolving it, @samp{entropy-emacs} declared one internal variable
@samp{entropy/emacs-org--src-info} for storing the info generated by func
@code{org-babel-get-src-block-info} and @code{org-babel-exp-src-block}
temporally for using for func @code{org-babel-confirm-evaluate}, the info
getted thus will contain babel block name rathan the origin one
generated within the process.

@item
@strong{Org auto insert custom id:}

Each headline has it's intential properties, one of them is
@samp{CUSTOM_ID} which is an headline identifier for be distinguished
with parents or other headlines.

Manually inserting or setting @samp{CUSTOM_ID} was the default method for
org users, but it's painful for doing thus with dozen of headlines,
@samp{entropy-emacs} gives the way for automatically insert @samp{CUSTOM_ID}
for all headlines within current org file buffer. These was sets of
functions:
@enumerate
@item
@code{entropy/emacs-org-add-ids-to-headlines-in-file}
@item
@code{entropy/emacs-org-auto-add-ids-to-headlines-in-file}
@end enumerate

The first one gives the forcing way for inserting @samp{CUSTOM_ID} to
each headline while one of them doesn't have one, and the second
otherwise for the state just when the option comment string in place
somewhere in current org file, i.e. '#+OPTIONS: auto-id:t'.

Don't like the human readable id style, these two automatically func
gives the id format as the numeric series with the prefix 'h-', this
mechanism reducing the possibility for conficting @samp{CUSTOM_ID}
occurence.

@samp{entropy-emacs} gives the auto way for automatically adding
headlines ids before save the org file who contained @samp{auto-id}
option, it's useful for the convenience way.

@item
@strong{Org tag inserting:}

Org designed with headline tag for sortting or filter dealing with,
each headline can has several tags sperated by colon, tag in current
buffer can be cached in @samp{org-file-tags} for query insertting, this
feature can also be retreived as global org files with agenda files.

@samp{entropy-emacs} using cousel extension for enhancing the using
experience of insertting tags, the func @code{counsel-org-tag} provides
the feature. By default, @samp{entropy-emacs} restricted tag list
collection scope via globle (with all agenda files), so that you can
quickly query tags from all existed ones to prevent create the
conflicts with messure spelling similarities of the same meaning.

Call the feature by keybinding as same as the origin org tag
insertting as for @samp{C-c C-q}.

@item
@strong{Org image drop and down:}

Org file as the simple rich txt file can be referred with images,
files, or other file type, the default inserting way was using the
manually type coding with the format as @samp{[[link location][content description]]}, or
you can drop down the file with gui mounse refers as other gui
application does, this feature provided by melpa package
@uref{https://github.com/abo-abo/org-download, org-download} but just with image thing as.

@enumerate
@item
image drop and down by local (just support on emacs gui port)
@item
image download from url
@item
capture screenshot with external tools
@end enumerate

Image drop and down for org buffer was handled by DND handle
@samp{org-download-dnd}, you don't need to know the detailes sticking
within this handle, here just to show the general process passing
by. Onece you draging one image file from system filesystem manager
e.g. Explorer(windows), Nautilus(linux gnome) @dots{} , to emacs gui
frame and pointed into the actived org buffer, @code{org-download-dnd}
will insert the image link which redirected to the will placing
image location.

The simple way for insert image source from other location was
through the way by downloading url method, and this is the second
feature of @samp{org-download} to handle the image insertting action. The
interactivation was simply just by calling interactive function
@code{org-download-image} soon as.

Depending on downloading way, @samp{org-download} also gives the try for
providing the image capture to insert func, this called
@code{org-download-screenshot}, literally meaning point to 'download' as
the way of this operation was steps sequenced as:

@enumerate
@item
Calling external gui screenshot application tracked by emacs
subprocess and waiting for return the image captured url.
@item
Using @code{org-download-image} to handle the reponse as the func it
provision.
@end enumerate

They are the three way of @samp{org-download} providing for image quickly
insertting.

@samp{entropy-emacs}'s hacking on @samp{org-download}:

@enumerate
@item
Patching org download inserting process support unicode file
name:

Origin @samp{org-download-method} was 'directory and using the process
snippet below to extracting the filename url to inserted into org
file:
@lisp
(org-download--fullname link ext)
@end lisp

While the argument link was combine with unicode file name, the
link generated by it will contained the hexo chars for excaped
the conflicated part of web url rule. Commonly it's useful and
normally.

But with some url string having the cjk or other unicode string
internally, hexo escape method was actually right for preventing
link follow analyzing error for some external software but the
human meaning reading available has for user of reading
currently. Thus, I given the specified @samp{org-download-method} for
falling back with the as-it link string presentation while
inserting the target image url string into org buffer's current
point:

@lisp
(defun custom-org-download-method (link)
        (org-download--fullname (org-link-unescape link)))
(setq org-download-method 'custom-org-download-method)
@end lisp

Which was the function replace the origin one 'directroy.

@item
Fallback dnd process redefined:

Org download will send the unused dnd action to the origin emacs
internal dnd handle, as the image open will still opened in
buffer while you using @samp{C-g} key quiting current behaviour came
from org-download, the image displaying effection will deliver to
the emacs internal default dnd file handle, it's violating the
user operation expection, as that I comment the fall back dnd
handle process snippet in func @code{org-download-dnd-fallback}.

@item
Org capture windows port external application setting:

When on w32 platform, org-download didn't give the capture image
method effectively, the core for it was the problem for finding
the screenshot (free liscense) application with cli interface as,
@samp{entropy-emacs} givies the try for windows internal public
(non-free) screenshot tool @samp{SnippingTool.exe} to using as it for.

As the default keybinding for the screenshot with
@samp{org-download-screenshot} as @samp{C-c p}.

Althouth WIN10 will removing it soon as the promotion while start
this minor tool now, but @samp{entropy-emacs} will finding the other
way for resolving this problem following Microsoft's developing
policy as well. Of course, you can specific you own screenshot
tool by specifying the custom-variable
@samp{entropy/emacs-win-org-download-screenshot-method} with the
default temporally screenshot filename customed by
@samp{entropy/emacs-win-org-download-file-name}.

@item
Capture screenshot image in org capture temporally buffer:

Commonly, the screenshot feature of org-download will working
well in the buffer with the actual based file and the unique
buffer name, unless for the buffer temporally which maked as org
capture behaviour. That's means in org cature buffer, org
download can not insert the image file-name correctly because of
that it can not check the true @samp{buffer-file-name} for calulating
the relative path between image file location and the current
buffer file.

Origin org download link inserting func
@code{org-download-insert-link}, using @code{(file-name-directory
     (buffer-name))} for generate the buffer-file-name but this was
not working on the temporally buffer, the whole relative link
path return snippet process will not worked as well yet:
@lisp
(defun org-download-insert-link (link filename)
  (if (looking-back "^[ \t]+" (line-beginning-position))
      (delete-region (match-beginning 0) (match-end 0))
    (newline))
  (insert
   (concat
    (funcall org-download-annotate-function link)
    "\n"
    (if (= org-download-image-html-width 0)
        ""
      (format "#+attr_html: :width %dpx\n" org-download-image-html-width))
    (if (= org-download-image-latex-width 0)
        ""
      (format "#+attr_latex: :width %dcm\n" org-download-image-latex-width))
    (format org-download-link-format (file-relative-name filename (file-name-directory (buffer-name))))))
  (org-display-inline-images))
@end lisp

You can see the last code snippt:

@example
(format org-download-link-format (file-relative-name filename (file-name-directory (buffer-name))))
@end example

It's will return the wrong path name when @samp{file-name-directory}
gives the nil return value.

As on @samp{entropy-emacs} gives the the patching for replacing
@code{(buffer-name)} with the self defined func
@code{entropy/emacs-org--odl-judgement-whether-capture-name} with the
full process dealing with the messure capture-buffer name.

@item
Image link insert automatically adjusting insert position
feature:

This feature provision of which judges the current cursor point
looking at where it is and automatically doing the inserting
position adjusting follow below rules:

@itemize
@item
@emph{Point at beginning of empty line:}

Insert link in current point.

@item
@emph{Point at middle or end of empty line:}

Insert link in current point.

@item
@emph{Point at end of none-empty line:}

Insert the link under of current line with newline creating.

@item
@emph{Point at partition case of none-empty line:}

Insert the link under of current line with newline creating.
@end itemize

@item
Auto indented link position:

When the customize variable @samp{org-adapt-indentation} was enabled
in current org buffer, automatically indenting the link position
after insert the link string by org-download.
@end enumerate

@item
@strong{Poporg (Edit docstring with org mode temperally):}

In emacs commmonly working with, docstring editting for func or src
context was commented editting operation and manually doing as
default.

@samp{poporg} was one melpa package who provide the feature for
automatically editting docstring by cut the region of docstring into
the popup temporally buffer with org-mode actived. In this case you
can save the docstring by the operation @code{save-buffer} or triggering
it with it's keybinding @samp{C-x C-s}, or discarding the editting with
@code{kill-buffer} or keybinding @samp{C-x k}.

@samp{poporg} was the minor tool used for conveniently did. It support
lots of src content with the detectivation rely on the grammer
analyzer as C using '@emph{* *}' as the comments region flags as so,
active @samp{poporg} while current cursor point was between the src refer
comment flags by keybinding @samp{C-c "}.
@end itemize

@node Miscellaneous emacs internal setting
@subsection Miscellaneous emacs internal setting

Emacs consists of various modes and sets of basic tool chains, all of
them are with the highly customizable with refer custom
variables. Each custom variable gives the default value setting.

But, not each defautl custom variables value given was satisfied for
all user, and some was not suit with @samp{entropy-emacs}.

And for with some minor enhancements or the minor tool adding was also
the necessaries for @samp{entropy-emacs}.

Thus, both the default setting modification and the other minor sets
did by @samp{entropy-emacs} are mischellaneous setting for as.

This section was the introduction for thus.

@itemize
@item
@strong{Dired colorful visual style:}

Dired was emacs internal filesystem viewer as the functioanl as w32
explorer or the nautilus for gnome (gnu/linux desktop manager), the
default visualization of it was ordered as the plain style.

For giving the mordern UI for dired was powered by two melpa
package:

@enumerate
@item
@samp{dired-rainbow}:

Extended file highlighting according to its type.

@item
@samp{all-the-icons-dired}

Extended file stick logo according to its type.
@end enumerate

You can chosen one of them by setting custom variable
@samp{entropy/emacs-dired-visual-type} with two value alternative:

@itemize
@item
"simple-rainbow" : using ‘dired-rainbow’.
@item
"all-the-icons" : using ‘all-the-icons-dired’
@end itemize

@item
@strong{Backup and auto-save config:}

@samp{entropy-emacs} disabled the auto backup file which functional of
emacs to gen the copy of current buffer-file before modifying
applied to it. Most of people using git or other vcs (version
control system) to manage the file version, thus the backup for the
file was not necessary as the default setting.

Otherwise, the feature auto saving file content was needed for
preventing the accident for broken the current buffer editting when
you haven't saved it immediately.

@item
@strong{Smooth scrolling buffer:}

Buffer scrolling in emacs was usually along with page jumping, up to
set the current line in the middle of the screen. This not suit with
the user who get the habbits from other text editor which always
scrolling the page along with the line jumping.

@samp{entropy-emacs} defined the func
@code{entropy/emacs-basic-smooth-scrolling} for emulating the behaviour
as so.  This func was interactive, you can active this feature by
calling it by 'M-x'.

@item
@strong{Auto sudo editting:}

When using emacs on unix like OS, visiting or editting high
permission required file will using emacs @uref{https://www.gnu.org/software/tramp/, tramp} feature, the
manually way for it will cost time for inputting the special file
path link, @samp{entropy-emacs} using melpa package @samp{auto-sudoedit}
giving the auto way as so.

You don't need to active any func manually or given sets of setting,
just using @code{find-file} or query and open permission needed file
using dired or other emacs internal or file open extension cmd
commonly, auto-sudoedit will auto detective the permission needed
and prompt for executing the account accessable operation.

@item
@strong{Epa enabled by default:}

Epa (EasyPG) was the emacs internal feature for auto encrypt and
decrypt gpg/pgp tool, @samp{entropy-emacs} enable it at emacs session
initial step by @code{(epa-file-enable)}.

@item
@strong{Kill ring browsing:}

Kill ring save the all yank strings into the circle list, emacs
support paste the history yanking according to the circle turns.

Melpa package @samp{browse-kill-ring} was the extension for it aimed to
provide the feature for browsing kill ring history in explicit way
with yanking choosing functional.
@end itemize

@node Font specific
@subsection Font specific

Emacs support multibyte fonts setting and the rich features for each
part of face refer.

@samp{entropy-emacs}'s initial config file @samp{entropy-emacs-font-set.el} was the
collection fonts config for as.

@samp{entropy-emacs} given the default ttf/otf fonts provission internally,
all the fonts given were opensource type without any warranty. we use
them for the defautls font setting turns on with custom variable
@samp{entropy/emacs-font-setting-enable} which was the key for using us
defautl font setting layout.

Our fonts config feature provide three type of language scripts type:

@itemize
@item
latin
@item
cjk
@item
symbol chars
@end itemize

While the latin was the most wild using script covered over code
source and doc built or read. We using 'Noto' from google, 'Source
code pro' from Adobe be choices for latin script fonts specification.

And then cjk script was using for multibyte and unicode language
encoding char presentation, emacs needed hands specific for it as the
especially on windows platfrom that will going wrong when cjk fonts
config with mistake or uncomfortable. we use 'Droid Sans' for chinese
and japanese, 'Noto Serif CJK KR' for Korea.

some symbol char refer to unicode will be lost of system font list, we
use 'symbola' one of the wild unicode encoding covering font
collection.

when your first using @samp{entropy-emacs}, if you want to using our font
config, you may want to manually install all the fonts archived
@uref{https://sourceforge.net/projects/entropy-emax64/files/entropy-emacs_hitch/20190505/, here}. Or you will recieve the warning at the startup but without any
feature lost, thus you can install them in any time.

@node Major modes for programming
@section Major modes for programming

Most major-modes contained the basic coding experience as syntax
highlight and the xref code snippet defination jumping
functional. Although it's the basic not upper to full sensitively
cheerful user experience.

@samp{entropy-emacs} using dozen melpa extensions to extending the
presented major modes' feature for enhancing more and more modes
experience individually. The main extending purpose was sticking on
the coding completion, based on @samp{company-mode} which was the coding
completion framework for any scences.As well, eachs major modes
extending were including the coding interactive sth refer, coding
folding and expanding uppon the region or pair punctuations are adding
so.

@samp{entropy-emacs} treats emacs as the IDE (i.e. integrated development
environment), extended with third-party lanuage servers, with the
quickly ripened for @uref{https://github.com/microsoft/language-server-protocol, Microsoft language server}, we are trending to use
the LSP as the IDE core component, its powerful with unified
crossplatform protocol defination and ripened communitiy driven. But
for those old IDE configuration (i.e. individually un-unified code
sever) were remained in @samp{entropy-emacs} and with full supported as
before. 

The switcher for @samp{lsp} and the old IDE configuration is customized
variable @samp{entropy/emacs-use-ide-type} whose valid values are 'lsp or
'traditional.

Follow sections given the description for each major modes which have
been enhanced the extending feature details informations.

@menu
* C and C++::
* Php::
* Html and Css::
* Javascript::
* Web front-end realtime previewer::
* Python anaconda::
@end menu

@node C and C++
@subsection C and C++

@multitable {aaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaa}
@headitem @strong{IDE type}
@tab @strong{language server}
@tab @strong{completion support}
@tab @strong{xref-defination support}
@item lsp-mode
@tab @uref{https://clang.llvm.org/extra/clangd.html, clangd}
@tab yes
@tab yes
@item traditional
@tab @uref{https://github.com/Sarcasm/irony-mode, irony-mode}
@tab yes
@tab yes
@item 
@tab 
@tab 
@tab 
@end multitable

@itemize
@item
@strong{Lsp-mode for cland eemacs configuration:}

Common lsp-mode configuration. 

@item
@strong{irony-mode eemacs configuration:}

@enumerate
@item
Using @uref{https://github.com/Sarcasm/irony-mode, irony-mode} to giving the project code defination review and
jumping feature.

@item
Using @samp{company-c-headers} to giving the project header file query
completions.
@end enumerate

@samp{irony-mode} based on the irony-server which has been compiled for w32
platform within @samp{entropy-emacs}, but needed compiling manually on
linux with dependencies installed e.g. cmake, clang @dots{} (We do not
packing the server binary on linux because for ths platform across
conflicated, thus x86 and arm or other cpu platform can not using the
same binary.)

Other feature extending are minor, simple file compiling on WINDOWS OS
was given as function @code{entropy/emacs-c-win-c-compiler} which using
mingw gcc for the compiler and with fixed library linking as for.
@end itemize

@node Php
@subsection Php

@multitable {aaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaa}
@headitem @strong{IDE type}
@tab @strong{language server}
@tab @strong{completion support}
@tab @strong{xref-defination support}
@item lsp-mode
@tab @uref{https://github.com/felixfbecker/php-language-server, php-language-server}
@tab yes
@tab yes
@item traditional ide
@tab @uref{https://github.com/xcwen/ac-php, ac-php}
@tab yes
@tab yes
@end multitable

@strong{Lsp-mode php-language-server eemacs configuration:}

Common lsp-mode instruction

@strong{Ac-php eemacs configuration:}

Php mode was derived from C-mode, familiar syntax-table and grammer
refer so that the syntax highlight was not needed to extend.

The main extending for was coding completion, we using @samp{company-php}
for giving thus. Binding with @samp{M-p} for activation.

@node Html and Css
@subsection Html and Css

emacs internal default web front-end major modes html and css mode are
user basically with simple func interactively support, we use melpa
package @uref{http://web-mode.org, web-mode} for the enhancements for html group markup language
but for css as.

web-mode provide sets of mordern features as for.  Tag folding and
expanding with @uref{https://github.com/smihica/emmet-mode, emmet-mode}'s abbrevation tag editting, giving the more
sensitive web refer coding.

Our self built func @code{entropy/emacs-web-browse-web-buffer} can quickly
browse the current html page out of using external browser for
previewing as the way of quickly did. it's binding to @samp{C-<f1>}.

Both of html and css buffer can be tidy up with normally code style
using @uref{https://github.com/yasuyk/web-beautify, web-beautify} package which required nodejs path searched and the
npm refer packages installed.

@multitable {aaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaa}
@headitem @strong{IDE type}
@tab @strong{language server}
@tab @strong{completion support}
@tab @strong{xref-defination support}
@item lsp-mode
@tab @uref{https://github.com/vscode-langservers/vscode-html-languageserver, html}
@tab yes
@tab yes
@item traditional
@tab html: no
@tab yes (@uref{https://github.com/osv/company-web, company-web})
@tab no
@item 
@tab css:  no
@tab yes (company-capf)
@tab no
@end multitable

@node Javascript
@subsection Javascript

JS development IDE @uref{https://github.com/mooz/js2-mode/, js2-mode} was the one for given such as repl and
syntax checking and morden syntax highlighting feature for js coding
which used in @samp{entropy-emacs} for be replaced with origin js major
mode.

@multitable {aaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaa}
@headitem @strong{IDE type}
@tab @strong{language server}
@tab @strong{completion support}
@tab @strong{xref-defination support}
@item lsp-mode
@tab @uref{https://github.com/theia-ide/typescript-language-server, typescript-language-server}
@tab yes
@tab yes
@item traditional
@tab @uref{https://github.com/ternjs/tern, tern}
@tab yes (@uref{https://github.com/ternjs/tern, company-tern})
@tab yes
@end multitable

@node Web front-end realtime previewer
@subsection Web front-end realtime previewer

@uref{https://github.com/netguy204/imp.el, impatient-mode} and @uref{https://github.com/skeeto/skewer-mode, skewer-mode} was two included melpa extension for
providing the web front-end realtime previewer feature.

@itemize
@item
@strong{skewer-mode:}

@samp{skewer-mode} provides js code snippet realtime evaluation feature,
it emulates the real-time evaluation mechanism upon emacs elisp
environment, using the way of the interaction of synchronizing with
external browser's internal javascript engine, evaluating the codes
snippet within current editting buffer. It support the repl by the
same way as well.

It's mechanism for:
@quotation
At first, daemon of one http server implemented by elisp programe
@uref{https://github.com/skeeto/emacs-http-server, simple-httpd} enabled for be as the interaction module with external
browser, then loading the js script for the server (as server instance
), as the same time, open external browser for listening changes of
the server mentioned before.

Later, each buffer modification will be sent to the server, and
external browser tracking the response.
@end quotation

Full process enable just using one func calling @code{run-skewer},
immediately then let your external browser directed to one page
@uref{http://127.0.0.1:8080/skewer/demo} , this page was the one previewing
all results generated by @samp{skewer-mode}.

@samp{skewer-mode} support css well, for css html and javascript, it
divided three minor-modes individually and functionally purpose as
the list below:

@example
The keybindings for evaluating expressions in the browser are just
like the Lisp modes. These are provided by the minor mode skewer-mode.

* C-x C-e: Evaluate the form before the point and display the result
 in the minibuffer. If given a prefix argument, insert the result into
 the current buffer.

* C-M-x: Evaluate the top-level form around the point.

* C-c C-k: Load the current buffer.

* C-c C-z: Select the REPL buffer.


The result of the expression is echoed in the minibuffer.

Additionally, css-mode and html-mode get similar sets of bindings for
modifying the CSS rules and HTML on the current page.

CSS

* C-x C-e: Load the declaration at the point.
* C-M-x: Load the entire rule around the point.
* C-c C-k: Load the current buffer as a stylesheet.

HTML

* C-M-x: Load the HTML tag immediately around the point.

Note: run-skewer uses browse-url to launch the browser. This may
require further setup depending on your operating system and personal
preferences.
@end example
@end itemize


You can touching @samp{C-c C-z} to active repl for js within js2-mode
buffer.

@itemize
@item
@strong{impatient-mode:}

@samp{impatient-mode} named as the meaning with humorous as the read-time
previewing moods given, it was the one relative by @samp{skewer-mode}'s
region partitial previewing mechanism, it's full buffer real-time
previewer as for. The core purpose for is to monitoring the html
buffer modification and so. The same well as using the simple http
server as @samp{skewer-mode}, it need to manually adding the files in the
same folder of css or html files along into the server.

When one folder structer list as:
@example
~/:
 |____index.html
 |____index.css
@end example

Thus we can following few steps for previewing the @samp{index.html} and
it's css file by @samp{impaitent-mode}, that's to say if you want the
index html file be rendered with all the references as above, you
need to manually adding them into server by call @code{impatient-mode}.

@enumerate
@item
enable internal web-server by @code{httpd-start}
@item
open @samp{index.html} and starting @samp{impatient-mode} and external
browser open link @uref{http://localhost:8080/imp/live/index.html/}
automatically at the same time.
@end enumerate

And now your index html file will be rendered real-time in this web
page. If you want to adding the css refer into, switching to the css
file buffer and executed above steps again with just replacing the
html file as instead of css file at the same meaning.

@strong{Limitations:}

All the linkage file must under the same directory tree. Thus
impatient-mode just the one for html design layout tool, otherwise
for the meaning as just for the single file previewing as the css
html js all in one embedding file as for.
@end itemize

@node Python anaconda
@subsection Python anaconda

We using emacs built-in major-mode @samp{python-mode} for coding python codes.

@multitable {aaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa} {aaaaaaaaaaaaaaaaaaaaaaaaa}
@headitem @strong{IDE type}
@tab @strong{language server}
@tab @strong{completion support}
@tab @strong{xref-defination support}
@item lsp-mode
@tab @uref{https://github.com/palantir/python-language-server, pyls}
@tab yes
@tab yes
@item traditional
@tab @uref{https://github.com/proofit404/anaconda-mode, anaconda-mode}
@tab yes (@uref{https://github.com/proofit404/anaconda-mode, company-anaconda})
@tab yes
@end multitable

@strong{python-mode eemacs specification}

By defautly, we using @samp{python3} be the primary python shell, that it
was the most recommendation for thus.

@node Packages enhancements and introduction
@section Packages enhancements and introduction

@menu
* Ivy and Helm::
* Emacs-W3m::
* Elfeed::
* Gnus::
@end menu

@node Ivy and Helm
@subsection Ivy and Helm

Ivy was emacs @samp{M-x} enhancements tool framework, it provides the
feature of listing candidates with extra operation given.

The internal @samp{M-x} replacement is swiper, using the same keybinding as
it but with the interactive interface visualized as:

@example
+-----------------------------------+
| I                                 |
|                                   |
|                                   |
|                                   |
|                                   |
|                                   |
|                                   |
|                                   |
+-----------------------------------+
|Choose your candidates:            |
+-----------------------------------+
|candidates:                        |
|1.apple                            |
|2.banaa                            |
|3. ..........                      |
+-----------------------------------+
@end example

Aspect oriented for framework, ivy provides ability for building extra
extension based the query promting listing sytle as upon , sets of
presented feature going collection was @samp{counsel}.

@samp{counsel} including commonly used tool e.g. @code{counsel-find-file}
replaced @code{find-file}.

@itemize
@item
@strong{counsel given for file based:}

@enumerate
@item
@samp{counsel-org group}

@enumerate
@item
coiunsel-org-goto: searching Org outlines, located quickly.

@item
counsel-org-goto-all: searching all org buffers listing
under current emacs session.
@item
counsel-org-capture: query selecting org capture templates.

@item
counsel-org-entity: query inserting entity char e.g. À ℘ δ π etc.
@end enumerate

@item
couinsel-yank-pop group: similiar as @code{browse-kill-ring}.

@item
counsel-recentf: show and query for recent files opened.

@item
counsel-ibuffer: ibuffer using ivy interface.

@item
counsel-bookmark: bookmark chosen extended for
@code{bookmark-bmenu-list}, as it's quickly view port.

@item
counsel-mark-ring: query selecting mark position.

@item
counsel-unicode-char: query insert unicode char with name
specification e.g. 00000C FORM FEED (FF)
@end enumerate

@item
@strong{counsel system config:}

@enumerate
@item
counsel-face: face information query for filter.

@item
counsel-set-variable: setting local variable by query prompt
@end enumerate

@item
@strong{counsel programming helper:}

@enumerate
@item
counsel-css: css mode css selector ivy list.

@item
counsel-colors-web: web mode color string visualized query prompting.

@item
counsel-git-log: query git log quickly.

@item
counsel-company: using ivy interface to show company backends
candidates.

@quotation
Notice: bug that can not cancel company-mode origin tooltip
when @samp{C-g} for this command.
@end quotation
@end enumerate

@item
@strong{ivy read action:}

Extra action supported within ivy interface, it called
@samp{ivy-read-action}, it has the built in ones and also can be
customized as extension ports.

Internal ivy-read-action has them:

@enumerate
@item
@samp{C-M m}

Repeately selected candidates.

@item
@samp{C-M j}

Force executing operation with current input string.

origin RET key will cover current inputs as instead of any
matched candidate list with ivy interface, thus this action is
feature as thus.

@item
@samp{C-c C-o}

Collected all current candidate into the temporary buffer for be
occurrence so.

@item
@samp{M-o}

Expand listing other specific extra actions.

This action was the leader for other internal extra actions and
user specifications did as, the defination former for thus can be
using the demo as @code{counsel-describe-face}:
@lisp
(ivy-set-actions
 'counsel-describe-variable
 '(("I" counsel-info-lookup-symbol "info")
   ("d" counsel--find-symbol "definition")))
@end lisp
@end enumerate
@end itemize



@uref{https://emacs-helm.github.io/helm/, Helm} was the another one extension similiar with ivy did, but with
more powerful. We do not using it by default because it's heavy volumn
as for. But we using other minor tool based on it e.g. @uref{https://github.com/syohex/emacs-helm-ag, helm-ag} which
binded to @samp{C-c j}.

@node Emacs-W3m
@subsection Emacs-W3m

Emacs internal browser eww was pure and enough for simple text web
browing using as. we also combine @samp{emacs-w3m} into @samp{entropy-emacs} for
providing full rich browsing experience for terminal or for keeping
the using feeling constant full with emacs as well.

@quotation
One reason for doing this was that emacs now can not retrieving https
content using the external proxy.
@end quotation

The origin keybindings and UI default setting for emacs-w3m was minor
strange as so, we hacking thus for:

@itemize
@item
UI reconfig
@item
Adding external browser quickly going for by keybinding @samp{B}.
@item
Automatically proxy with specific rule setting.(using feature powerd
by @uref{https://github.com/c0001/entropy-proxy-url, entropy-proxy-url})
@end itemize

For using @samp{emacs-w3m} you need the external cli programe w3m
installed, see the w3m home page @uref{http://w3m.sourceforge.net/}.

And onekey for open it with @samp{M-x w3m}. Go go go @dots{}

@node Elfeed
@subsection Elfeed

Did you thought about for feeding rss rely on emacs only?

Melpa package @uref{https://github.com/skeeto/elfeed, elfeed} given the try for. The only operation you need to
do is calling @samp{M-x elfeed} thus as.

Elfeed was the rss feeds viewing, management program written of elisp,
the only alternative external requirements is 'curl', which for push
the feeds retrieving task for subprocess for reducing emacs self
performance consumption.

origin elfeeds feeds naming string querying searching support was not
support cjk unicode as, we given the try for hacking with by using
self built func @code{entropy/emacs-tools-elfeed-filter-by-tag}, as more
hacking see below:

@itemize
@item
Feature adding of searching feed according to feed title
name. Binding to @samp{A}.

@item
Tag filter with query promting, binding to @samp{B}.

@item
Auto rename feed-title with hyphenation '-'.

This is for fixing the problem by feed title name with space that
can not be detective by origin internal funcs.

@item
Repeatly removing feeds.

@item
Update feeds using proxy.

Through manually setting proxy config through custom variable
@samp{entropy/emacs-elfeed-proxyfeeds-regexp-list}. (with prompt for
input as @uref{http://127.0.0.1:1080})

Proxy updating with three methods:

@enumerate
@item
using manually feeds selecting by
@code{entropy/emacs-tools-elfeed-update-proxy}.
@item
update feeds with regexp matching by
@code{entropy/emacs-tools-elfeed-update-proxyfeeds-regexp-match}.
@item
upate all null feeds (without and entries obtained yet), using
@code{entropy/emacs-tools-elfeed-proxy-update-all-nil-feeds}.
@end enumerate
@end itemize

All the feeds filter can be reset with short cut @samp{S}.

@node Gnus
@subsection Gnus

For now, we just given gnus simply try with the local file directory
location config with one custom variable
@samp{entropy/emacs-gnus-init-config} try see coding snippet for the
details.

@node Emacs on windows
@section Emacs on windows

Emacs was originally built for gnu/linux, compatible with UNIX-like
OS. Windows port was built for be as the reason by:
@quotation
We support GNU Emacs on proprietary operating systems because we hope
this taste of freedom will inspire users to escape from them.

excerpt from:
@uref{https://www.gnu.org/software/emacs/manual/html_node/emacs/Microsoft-Windows.html#Microsoft-Windows}
@end quotation

'Taste' notice for, but more than this prudent meaning.

I thought the reason for 'taste' annotaion quoting for this as the
declaration was that WINDOWS was designed by the different tree fork
sibling as the rebeler against UNIX. Thus the OS internal process
mechnism was not full compat with the origin emacs design conceptual.

But, actually I am one emacser port on w32. Mine experience was fully
sensitive acquiring the almost fully features covered as on linux,
just with some explicit non-compatible feature which came from the OS
feature forking on. One of them was shell interface bash intern and
the rest was some feature's bug caused by the w32 api iteration.

Although, the hacking for emulating the whole linux emacs using
environment by us was not full featured as, but I thoughts following
WINDOWS emacs using was enough for daily using just with minor trouble
for.

@menu
* Bash and unix tool chains for windows::
* Portable emacs environment on windows::
* Notice for key touching on windows::
@end menu

@node Bash and unix tool chains for windows
@subsection Bash and unix tool chains for windows

We using Msys2 as the bash shell emulator for emacs windows port, this
is also the wild used of other windows gui to do with. Msys2 was the
integrated project consists of cygwin and mingw, both of them are the
windows gnu tool chains and differences of whether abiding with the
POSIX rule.

For integrated Msys2 into emacs, was using the way for adding the
tool-chain path binding with emacs internal path variable, both from
the shell path detectived "PATH" obtained by @code{(getenv "PATH")} and the
@samp{exec-path}.

@node Portable emacs environment on windows
@subsection Portable emacs environment on windows

Emacs has the relative path specification variable
@samp{invocation-directory} and @samp{data-directory}, both of them are
internally built which can auto re-set before emacs started.

The portale of emacs config was depent on the config folder portable
refer setting, i.e. HOME path portale specification. You can using
those two variable to be the bridge to directed to the home path using
the elisp code indicating:
@lisp
(defvar device-root (concat (substring invocation-directory 0 -11) "Msys2/"))
(setenv "HOME" (expand-file-name (concat device-root "portable-HOME")))
@end lisp

As so, this config demo can be extending for each portable path
setting.

@node Notice for key touching on windows
@subsection Notice for key touching on windows

Emacs windows port distribution was built with mingw relied on msys2
toolchains, minor bugs was founded, the key touching bug especially.
@quotation
There's no key touching bug founded on WIN7, thus below description
was refer to WIN10.
@end quotation

On WIN10, the @samp{win} key was temporally frozen the other key taken up
when OS session recovery from screen lock state, this was the annoying
bug which caused by the new windows key chunks api refers, to recovery
this by touching @samp{win} key again.

@node Docs refers
@chapter Docs refers

@bye