;;; entropy-org-batch-refile-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-org-batch-refile.el

(autoload 'entropy/org-batch-refile-tags-read-and-do "entropy-org-batch-refile" "\
Refile by specifying the tag matched with interactively envrionment.

(fn TAG-REGEXP)" t)
(register-definition-prefixes "entropy-org-batch-refile" '("entropy/o"))

;;; End of scraped data

(provide 'entropy-org-batch-refile-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-org-batch-refile-autoloads.el ends here
