;;; entropy-adblockP-rule-analysis-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from entropy-adblockP-rule-analysis.el

(autoload 'entropy/adbp-rule-get-regexp-matchs-list "entropy-adblockP-rule-analysis" "\


(fn &optional INCT)")
(autoload 'entropy/adbp-rule-blacklist-match-url-p "entropy-adblockP-rule-analysis" "\


(fn URL &optional DEBUG)")
(autoload 'entropy/adbp-rule-update "entropy-adblockP-rule-analysis" "\
Update rulesets prompted with whether follow upstream or with
local cache only.

(fn &optional ARG)" t)
(register-definition-prefixes "entropy-adblockP-rule-analysis" '("entropy/adbp-"))

;;; End of scraped data

(provide 'entropy-adblockP-rule-analysis-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; entropy-adblockP-rule-analysis-autoloads.el ends here
